### PR TITLE
Improve mobile navigation

### LINKED ISSUE #2871: Hard to find feature documentation on mobile
I had a lot of trouble finding documentation on features like gRPC on mobile because

- There are two hamburger menus
- There is a Jump to drop-down with light text that I missed for a while. I think its uncommon to have to expand twice, once hamburger and once again

Screenshot_20200703-201904
Screenshot_20200703-201909

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

It is hard to navigate from one page to another in mobile view.

Modifications:

- Show the globel ToC instead of the page ToC when:
  - The current layout is single-column and ToC button is clicked.
  - The current layout is dual-column.
- Merge two hamburger buttons into one.
- Miscellaneous:
  - Adjust the right margin of social icons and hamburger button for
    aesthetics' sake.

Result:

- Fixes #2871

### CODE REVIEW

**Comment by anuraaga** [comment]
I guess this is up on armeria.dev now? I would increase opacity, especially when over the YouTube video it's pretty hard to read. Also noticed, if you first scroll then press the TOC button it shows an empty menu since the menu is scrolled already. This looks like broken behavior though.

**Comment by trustin** [comment]
@anuraaga I've just deployed this change to https://armeria.dev/docs/ What do you think?

**Comment by trustin** [comment]
Increased the opacity from 0.9 to 0.95. Looks better? ToC behavior needs a little bit more work. Will ping once done.

**Comment by trustin** [comment]
Ah, I didn't deploy the opacity change yet. Please check in a few minutes.

**Comment by anuraaga** [comment]
Implementation will be a lot of effort I think but one idea is merging the TOC into the sidebar on mobile. For example, when tapping Documentation, if it expanded the TOC just under that inline, it'd be intuitive I think, especially since then only one hamburger, and I think it wouldn't have the scroll issue.

**Comment by trustin** [comment]
Yeah, thought about that, too. Just wasn't sure if it's worth such an effort. Let me try a little bit anyways 😆

**Comment by trustin** [comment]
@anuraaga How does it look now? I merged two hamburger buttons finally. 😆

**Comment by trustin** [comment]
Thanks for quick reviews, folks!

**Pull request merged**
