### PR TITLE
Switch to Gradle

### PR DESCRIPTION
**Pull request by trustin**
for more flexible and customizable build

- [x] Call tomcat80-compat.groovy after compilation
- [x] Fix failing TomcatService tests
- [x] Javadoc and Xref generation
- [x] Make Sphinx site work without pom.xml
- [x] Apply Spring dependency-management-plugin
- [x] Checkstyle
- [x] Maven central publishing

---
This change is [Reviewable](https://reviewable.io/reviews/line/armeria/294)

### CODE REVIEW

**Comment by anuraaga** [comment]
Reviewed 14 of 1161 files at r1.
Review status: 12 of 587 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 2 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpi37klEoSGhtdPW70:-KSpi37lU4DwFs2rcWh2:b-hfizy6) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/.gitignore#L2)):*
> ```
> # Build output
> /build
> ```

Is there any difference between this and just
```
build
```
?

---

*[build.gradle, line 39 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpiZbti68eCK4nQ2pd:-KSpiZbti68eCK4nQ2pe:b-wdg4vh) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/build.gradle#L39)):*
> ```Gradle
> 
>         // Logging
>         compile "org.slf4j:slf4j-api:${property('slf4j.version')}"
> ```

JFYI, it can be convenient to use spring-dependencies-plugin to manage project dependency versions at the top level file without relying on referencing properties everywhere

---

*[gradle.properties, line 2 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpin6g7DH5G0ewGNfn:-KSpin6g7DH5G0ewGNfo:bxwgfby) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/gradle.properties#L2)):*
> ```INI
> group=com.linecorp.armeria
> version=0.27.1-SNAPSHOT
> ```

0.27.1.Final-SNAPSHOT

---

*[core/build.gradle, line 101 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpjHs596L3umN4yCRp:-KSpjHs596L3umN4yCRq:bj5bokw) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/core/build.gradle#L101)):*
> ```Gradle
>     [ 'main', 'test' ].each { scope ->
>         def inputDir = "${project.projectDir}/src/${scope}/thrift"
>         def outputDir = "${project.projectDir}/src/${scope}/gen-java"
> ```

While it can be a bit annoying, it is possible to set up gradle to properly generate thrift files into build directory, the magic usually involves something like

https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/main/groovy/net/ltgt/gradle/apt/AptPlugin.groovy#L185

Also recommend using gradle-thrift-plugin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by imasahiro** [comment]
>  Fix failing TomcatService tests
I guess following diff helps you https://github.com/line/armeria/pull/185/commits/2df01de44454a4feaaa3ffc833717be0aca9cb50#diff-7029647e428ac65865cd490bff3d5089R45

**Comment by trustin** [comment]
Review status: 11 of 587 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 2 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpi37klEoSGhtdPW70:-KStKkxGwQ76rDNpolOA:b-f5sr4j) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/.gitignore#L2)):*
<details><summary><i>Previously, anuraaga (Anuraag Agrawal) wrote…</i></summary>
> Is there any difference between this and just
> ```
> build
> ```
> ?
</details>
`build` is identical to `**/build` which may exclude directories like `src/main/java/...../build`

---

*[build.gradle, line 39 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpiZbti68eCK4nQ2pd:-KStL7HyRJVzhkWp9S6F:b-epwwx7) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/build.gradle#L39)):*
<details><summary><i>Previously, anuraaga (Anuraag Agrawal) wrote…</i></summary>
> JFYI, it can be convenient to use spring-dependencies-plugin to manage project dependency versions at the top level file without relying on referencing properties everywhere
</details>
Could you point me at the URL of the plugin? I couldn't find it..

---

*[core/build.gradle, line 101 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpjHs596L3umN4yCRp:-KStLVi_djmfctnvKWrN:b9jwzp0) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/core/build.gradle#L101)):*
<details><summary><i>Previously, anuraaga (Anuraag Agrawal) wrote…</i></summary>
> While it can be a bit annoying, it is possible to set up gradle to properly generate thrift files into build directory, the magic usually involves something like
> 
> https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/main/groovy/net/ltgt/gradle/apt/AptPlugin.groovy#L185
> 
> Also recommend using gradle-thrift-plugin
</details>
According to my experience, even with Apt plugin, having generated source files under `/build` was sometimes problematic with IntelliJ idea, although my current approach seems to work with IntelliJ IDEA 2016.2 even when I generate under `/build`.

I tried thrift-gradle-plugin (the jruyi one)  but it did not allow me to generate both main and test .thrift files. Should I try another one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by trustin** [comment]
>> Fix failing TomcatService tests
> I guess following diff helps you 2df01de#diff-7029647e428ac65865cd490bff3d5089R45

I actually made that change already, but it will fail anyway because Gradle copies the files under the resources directory to other directory than build/classes. Let me try to tell Gradle copy the resource files to the build/classes directory.

**Comment by trustin** [comment]
> I actually made that change already, but it will fail anyway because Gradle copies the files under the resources directory to other directory than build/classes. Let me try to tell Gradle copy the resource files to the build/classes directory.

Ah, you were suggesting a fix for `UnmanagedTomcatServiceTest`. Yes, you are right. Thanks for the fix!

**Comment by imasahiro** [comment]
*[build.gradle, line 39 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpiZbti68eCK4nQ2pd:-KSqqGn4X-LqPNXLUcHi:br3qv43) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/build.gradle#L39)):*
<details><summary><i>Previously, trustin (Trustin Lee) wrote…</i></summary>
> Could you point me at the URL of the plugin? I couldn't find it..
</details>
This is the pacakge he suggested.
`classpath "io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by imasahiro** [comment]
*[build.gradle, line 39 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpiZbti68eCK4nQ2pd:-KStVSztrbBhLBI_696M:b-kzpciw) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/build.gradle#L39)):*
<details><summary><i>Previously, imasahiro (Masahiro Ide) wrote…</i></summary>
> This is the pacakge he suggested.
> `classpath "io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE"`
</details>
```gradle 
def dependencyVersions = [
  'io.netty:netty-transport:4.1.5.Final',
  'io.netty:netty-transport-native-epoll:4.1.5.Final',
  'io.netty:netty-codec-http2:4.1.5.Final',
  ...
];
allprojects {
 apply plugin: "io.spring.dependency-management"
  ...
 dependencyManagement {
    dependencies {
      dependencyVersions.each { dependency it }
    }
 }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by anuraaga** [comment]
Review status: 9 of 587 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 2 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpi37klEoSGhtdPW70:-KStZ4iPMJQbaCq6HK3F:b-yj5p67) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/.gitignore#L2)):*
<details><summary><i>Previously, trustin (Trustin Lee) wrote…</i></summary>
> `build` is identical to `**/build` which may exclude directories like `src/main/java/...../build`
</details>
Oops - duh thanks.

---

*[core/build.gradle, line 101 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpjHs596L3umN4yCRp:-KSt_wyyBRekAQ8xyuFH:b-5w9vob) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/core/build.gradle#L101)):*
<details><summary><i>Previously, trustin (Trustin Lee) wrote…</i></summary>
> According to my experience, even with Apt plugin, having generated source files under `/build` was sometimes problematic with IntelliJ idea, although my current approach seems to work with IntelliJ IDEA 2016.2 even when I generate under `/build`.
> 
> I tried thrift-gradle-plugin (the jruyi one)  but it did not allow me to generate both main and test .thrift files. Should I try another one?
</details>
Hmm - I can't say I've ever had issues with files under build actually being included when using that AptPlugin code, though I do know that for annotation processing (which we don't use) it's important to use the right invocation of ./gradlew idea + opening in the IDE, don't think it's relevant to armeria though.

Didn't realize gradle plugin doesn't allow processing test - that's too bad :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by imasahiro** [comment]
*[core/build.gradle, line 101 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpjHs596L3umN4yCRp:-KStfJXbyIxNR29aqGov:b-n7g4gs) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/core/build.gradle#L101)):*
<details><summary><i>Previously, anuraaga (Anuraag Agrawal) wrote…</i></summary>
> Hmm - I can't say I've ever had issues with files under build actually being included when using that AptPlugin code, though I do know that for annotation processing (which we don't use) it's important to use the right invocation of ./gradlew idea + opening in the IDE, don't think it's relevant to armeria though.
> 
> Didn't realize gradle plugin doesn't allow processing test - that's too bad :(
</details>
If we need to generate both main and test thrift files, IIUC, need to write compileThrift task for each dirs. Here is the gradle script that generate both thrift files using gradle.plugin.org.jruyi.gradle.
https://github.com/line/armeria/commit/5ae842a39f4b84517ebce285de3fa5aefaed011f#diff-c197962302397baf3a4cc36463dce5eaR31

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by trustin** [comment]
Review status: 9 of 587 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/build.gradle, line 101 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpjHs596L3umN4yCRp:-KStwq8CMwsrVqLaiKc4:b-rt6z9e) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/core/build.gradle#L101)):*
<details><summary><i>Previously, imasahiro (Masahiro Ide) wrote…</i></summary>
> If we need to generate both main and test thrift files, IIUC, need to write compileThrift task for each dirs. Here is the gradle script that generate both thrift files using gradle.plugin.org.jruyi.gradle.
> https://github.com/line/armeria/commit/5ae842a39f4b84517ebce285de3fa5aefaed011f#diff-c197962302397baf3a4cc36463dce5eaR31
</details>
Actually, the CompileThrift task always adds the generated source directory to the main scope.
so.. running it for test .thrift files will end up with adding it to the main sourceSets which is not correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by trustin** [comment]
I used the dependency-management-plugin but kept the version numbers in the gradle.properties file so Sphinx can pull it in when it generates the web site.

**Comment by anuraaga** [comment]
Review status: 9 of 586 files reviewed at latest revision, 6 unresolved discussions.

---

*[build.gradle, line 162 at r4](https://reviewable.io:443/reviews/line/armeria/294#-KSvy01c4TqVZsoqqChX:-KSvy01c4TqVZsoqqChY:bh1cswq) ([raw file](https://github.com/line/armeria/blob/76268cc9de6e1a38cb30ce8c4e7e8a7af174debd/build.gradle#L162)):*
> ```Gradle
>     dependencies {
>         // JSR305
>         compile("com.google.code.findbugs:jsr305") {
> ```

compileOnly

---

*[build.gradle, line 167 at r4](https://reviewable.io:443/reviews/line/armeria/294#-KSvyCeQwx1JA3Kaw2_a:-KSvyCeQwx1JA3Kaw2_b:b57sekx) ([raw file](https://github.com/line/armeria/blob/76268cc9de6e1a38cb30ce8c4e7e8a7af174debd/build.gradle#L167)):*
> ```Gradle
> 
>         // Jetty ALPN support
>         compile("org.eclipse.jetty.alpn:alpn-api") {
> ```

Can use compileOnly for both of Maven's optional + provided AFAIU (if armeria doesn't reference this API directly, runtime is more appropriate though I believe)

---

*[build.gradle, line 250 at r4](https://reviewable.io:443/reviews/line/armeria/294#-KSvyrbBT2Q0cHuu2vX5:-KSvyrbBT2Q0cHuu2vX6:bvoa45o) ([raw file](https://github.com/line/armeria/blob/76268cc9de6e1a38cb30ce8c4e7e8a7af174debd/build.gradle#L250)):*
> ```Gradle
>     afterEvaluate { versionProperties.execute() }
> 
>     // Print only the interesting test result and progress.
> ```

```java
// Print only interesting test results and progress.
```

---

*[core/build.gradle, line 101 at r1](https://reviewable.io:443/reviews/line/armeria/294#-KSpjHs596L3umN4yCRp:-KSvxQoFyJzoAbv7UE4v:b-yjchuu) ([raw file](https://github.com/line/armeria/blob/0cc2ff72523abcb1df43126d8528d529dfc0377d/core/build.gradle#L101)):*
<details><summary><i>Previously, trustin (Trustin Lee) wrote…</i></summary>
> Actually, the CompileThrift task always adds the generated source directory to the main scope.
> so.. running it for test .thrift files will end up with adding it to the main sourceSets which is not correct.
</details>
Looking forward to line/gradle-thrift-plugin which solves this and also includes the binaries in the plugin :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by imasahiro** [comment]
*[build.gradle, line 21 at r4](https://reviewable.io:443/reviews/line/armeria/294#-KT7jveb1rFxoDADiuaB:-KT7jveb1rFxoDADiuaC:bs7onlb) ([raw file](https://github.com/line/armeria/blob/76268cc9de6e1a38cb30ce8c4e7e8a7af174debd/build.gradle#L21)):*
> ```Gradle
>     apply plugin: 'jacoco'
>     apply plugin: 'io.spring.dependency-management'
> ```

checkstyle plugin  is missing?

```gradle
    apply plugin: 'checkstyle'

    def checkstyleConfigDir = rootProject.file('settings/checkstyle/')
    checkstyle {
        configFile = new File(checkstyleConfigDir, 'checkstyle.xml')
        configProperties = ['checkstyleConfigDir': "$checkstyleConfigDir"]
        reportsDir = rootProject.file('build/checkstyle')
        toolVersion = '7.1'
    }
```

And add SuppressionFilter to checkstyle.xml.
```xml
  <module name="SuppressionFilter">
      <property name="file" value="${checkstyleConfigDir}/checkstyle-suppressions.xml"/>
  </module>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by trustin** [comment]
Review status: 9 of 588 files reviewed at latest revision, 7 unresolved discussions.

---

*[build.gradle, line 21 at r4](https://reviewable.io:443/reviews/line/armeria/294#-KT7jveb1rFxoDADiuaB:-KTClJSYJAINx4F7m9Jm:by5s982) ([raw file](https://github.com/line/armeria/blob/76268cc9de6e1a38cb30ce8c4e7e8a7af174debd/build.gradle#L21)):*
<details><summary><i>Previously, imasahiro (Masahiro Ide) wrote…</i></summary>
> checkstyle plugin  is missing?
> 
> ```gradle
>     apply plugin: 'checkstyle'
> 
>     def checkstyleConfigDir = rootProject.file('settings/checkstyle/')
>     checkstyle {
>         configFile = new File(checkstyleConfigDir, 'checkstyle.xml')
>         configProperties = ['checkstyleConfigDir': "$checkstyleConfigDir"]
>         reportsDir = rootProject.file('build/checkstyle')
>         toolVersion = '7.1'
>     }
> ```
> 
> And add SuppressionFilter to checkstyle.xml.
> ```xml
>   <module name="SuppressionFilter">
>       <property name="file" value="${checkstyleConfigDir}/checkstyle-suppressions.xml"/>
>   </module>
> ```
</details>
Thanks! Applied the plugin. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by imasahiro** [comment]
*[core/build.gradle, line 56 at r5](https://reviewable.io:443/reviews/line/armeria/294#-KTDfw17v4q5A2kx4r9j:-KTDfw17v4q5A2kx4r9k:buy8ied) ([raw file](https://github.com/line/armeria/blob/5a0d783d44d75207ae9d40b690f94e184894e99c/core/build.gradle#L56)):*
> ```Gradle
>     [ 'grpc-core', 'grpc-stub', 'grpc-protobuf' ].each {
>         compile("io.grpc:$it") {
>             ext.optional = true
> ```

compileOnly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by imasahiro** [comment]
*[build.gradle, line 13 at r5](https://reviewable.io:443/reviews/line/armeria/294#-KTDh-l73cu_HO8wKWoj:-KTDh-l73cu_HO8wKWok:bidbz7r) ([raw file](https://github.com/line/armeria/blob/5a0d783d44d75207ae9d40b690f94e184894e99c/build.gradle#L13)):*
> ```Gradle
> ext.repoStatus = getRepoStatus()
> ext.versionOf = { key -> project.property("${key}.version") }
> ```

How about apply eclipse and idea plugins?
```
allprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by trustin** [comment]
Review status: 7 of 588 files reviewed at latest revision, 9 unresolved discussions.

---

*[core/build.gradle, line 56 at r5](https://reviewable.io:443/reviews/line/armeria/294#-KTDfw17v4q5A2kx4r9j:-KTE4IEtdixdddCnJR5g:b-2q2h8j) ([raw file](https://github.com/line/armeria/blob/5a0d783d44d75207ae9d40b690f94e184894e99c/core/build.gradle#L56)):*
<details><summary><i>Previously, imasahiro (Masahiro Ide) wrote…</i></summary>
> compileOnly?
</details>
It seems like `compileOnly` scope doesn't work well with Javadoc task. Javadoc will warn about missing classes when processing `{@link ..}` tags for the `compileOnly` dependencies.

Let me leave this as-is given that the plan is to move the features with the optional dependencies into separate submodules. i.e. will solve in a follow-up PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294)*

**Comment by trustin** [comment]
@imasahiro @anuraaga Ready to be merged. Please review!

**Comment by anuraaga** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r6.
Review status: 9 of 588 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/line/armeria/294#-:-KTI-RT6Jv2pXKAbL0FH:bnfp4nl)*

**Comment by trustin** [comment]
I wonder if it is possible to configure the generated IntelliJ IDEA project to include the inspector and code style settings. A dev will not need to import the setting manually if that's possible.

**Comment by trustin** [comment]
Thanks, @imasahiro !

**Pull request merged**
