### PR TITLE
Bump to Netty 4.1.95.Final

### PR DESCRIPTION
**Pull request by hyperxpro**
Motivation:
Netty [4.1.95.Final](https://netty.io/news/2023/07/20/4-1-95-Final.html) is out and we should upgrade to it.

Modifications:
Upgraded Netty to 4.1.95.Final

Result:
Latest Netty version

### CODE REVIEW

**Comment by trustin** [comment]
@hyperxpro Hey :wave: Thanks for the PR!

**Comment by hyperxpro** [comment]
Ayyo @trustin 

Just getting started with Armeria. My next major project will be on it. Thanks for the great framework once again! :)

**Review by ikhoon — APPROVED** [review]
Thanks, @hyperxpro! 🙇‍♂️

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Review by minwoox — APPROVED** [review]
Thanks!

**Comment by trustin** [comment]
> Just getting started with Armeria. My next major project will be on it. Thanks for the great framework once again! :)

Looking forward to this, @hyperxpro! Once it goes to production, please consider adding it here: https://github.com/line/armeria/discussions/4626 :wink:

**Pull request merged**
