### PR TITLE
Avoid using `compileClasspath` to resolve POM dependencies

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

SLF4J dependency has been expectedly updated to 2.0.7 in the [1.24.3-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/linecorp/armeria/armeria/1.24.3-SNAPSHOT/armeria-1.24.3-20230814.032459-136.pom) although SLF4J 1.7.36 version is explcitly set as a dependency. https://github.com/line/armeria/blob/7d29cdf1c67fd9e23589cace86d54d3a84b5554e/dependencies.toml#L124-L124 https://github.com/line/armeria/blob/7d29cdf1c67fd9e23589cace86d54d3a84b5554e/build.gradle#L202-L202

After digging into the problem, Logback 1.4.8 added as `compileOnly` dependency in #5079 was the cause of the wrong SLF4J version in the POM file. It was weird that `compileOnly` dependencies affected `implementation` or `api` dependencies.

 `versionMapping` strategy declared in `java-publish.gradle` was the root cause of the problem. It resolves all variants including `complieOnly` to generate POM files.
https://github.com/line/armeria/blob/7d29cdf1c67fd9e23589cace86d54d3a84b5554e/gradle/scripts/lib/java-publish.gradle#L11-L16

Modifications:

- Changed the strategy to resolve dependencies only from `runtimeClasspath`.
  - It does not make sense to use `compileOnly` dependencies for `apiElements`.
  - The configuration is in the same format as shown in the Gradle documentation example. https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies

Result:

Fixed the wrong SLF4J dependency in the POM file.
Note that #5079 has not been released. So users are not affected by the regression.

### CODE REVIEW

**Comment by ikhoon** [comment]
Checked all generated POM files with the new strategy and all results were the same except for SLF4J version
```diff
*** ./armeria/1.24.3-SNAPSHOT/armeria-1.24.3-SNAPSHOT.pom       Wed Aug 16 12:00:18 2023
--- ./armeria/1.24.3-fixed-SNAPSHOT/armeria-1.24.3-fixed-SNAPSHOT.pom     Wed Aug 16 19:26:33 2023
***************
*** 31,37 ****
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
-       <version>2.0.7</version>
        <scope>compile</scope>
      </dependency>
      <dependency>
--- 31,37 ----
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
+       <version>1.7.36</version>
        <scope>compile</scope>
      </dependency>
      <dependency>
```

**Review by trustin — APPROVED** [review]
Thanks, @ikhoon!

**Review by jrhee17 — APPROVED** [review]
Thanks for debugging this tricky issue @ikhoon ! 🙇 👍 🚀

**Review by minwoox — APPROVED** [review]
Thanks! 👍 👍 👍

**Comment by trustin** [comment]
Let me close this PR since it's already been pulled into the main branch by `git subrepo pull` from `line/gradle-scripts`. Thanks, @ikhoon! :bow:

**Pull request closed without merging**
