### PR TITLE
Do not expose Guava's `ToStringHelper` from the public API

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

It's a bad idea to expose Guava classes from our public API because all
Guava classes are shaded into `com.linecorp.armeria.internal.shaded.guava`,
exposing the internal classes in the public API.

Modifications:

- Fixed the broken test in `javadoc/build.gradle`.
- Replaced `DynamicEndpointGroup.toStringHelper()` with `toString(Consumer)`.

Result:

- We do not leak internal classes in our public API anymore.

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
Oops, thanks!

**Review by ikhoon — APPROVED** [review]
Thanks!

**Comment by ikhoon** [comment]
> eckstyle] [ERROR] /home/ec2-user/actions-runner/_work/armeria/armeria/core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java:36:8: Unused import - com.google.common.base.MoreObjects.ToStringHelper. [UnusedImports]

Would you mind fixing the lint failure?

**Review by jrhee17 — APPROVED** [review]
Thanks @trustin 🙇 👍 🙇

**Comment by trustin** [comment]
Thanks a lot for fixing the lint error, @jrhee17 :bow:

**Pull request merged**
