### PR TITLE
Migrate docs client to webpack-dev-server.

### PR DESCRIPTION
**Pull request by anuraaga**
webpack-dev-server was deprecated, but then undeprecated and the replacement webpack-serve itself is deprecated.

Also adds a redirect to the path with a trailing slash to help with the confusing behavior we saw a while ago.

### CODE REVIEW

**Comment by ikhoon** [comment]
@anuraaga Thanks for nice work!
Could you update the license file?
`yarn licenses generate-disclaimer --prod > ../licenses/web-licenses.txt`

**Comment by anuraaga** [comment]
This only affects dev dependencies so the bundle's dependencies, and therefore licenses, aren't changed.

**Comment by ikhoon** [comment]
@anuraaga Ahh, I see. Thank you for migrating  `webpack-dev-server`!

**Comment by trustin** [comment]
Thanks a lot, @anuraaga !

**Pull request merged**
