### PR TITLE
Bump Spring Boot 3 and Spring versions

### PR DESCRIPTION
**Pull request by ikhoon**
- Spring 5.3.26 -> 6.0.6
- Spring Boot 3.0.2 -> 3.0.5

Note:

The direct dependency of `spring-web` is only used in tests. Spring 6 has been used by Spring Boot 3 as a transitive dependency. So the old Spring 5 version was not a problem to Spring Boot 3 modules.

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Review by trustin — APPROVED** [review]
:+1: Please resolve the conflict :-)

**Comment by ikhoon** [comment]
Resolved the conflict.

**Comment by minwoox** [comment]
Let me take a look at the failure.

**Comment by ikhoon** [comment]
It will be fixed if main branch is merged.

**Comment by minwoox** [comment]
Forget to approve. 😓 
Thanks a lot, @ikhoon! 😄

**Pull request merged**
