### PR TITLE
[WIP] Serve GraphQL IDE by Documentation service

### LINKED ISSUE #3706: Serve GraphQL IDE  by Documentation service
[GraphQL playground](https://github.com/graphql/graphql-playground) and [GraphiQL](https://github.com/graphql/graphiql) provide awesome features for GraphQL such as:
- Autocompletion 
- Error highlighting
- Browsing GraphQL document
 
Armeria's documentation service leverages GraphQL IDE to support browsing and invoking services.
If a `GraphqlService` is bound to a server, a `DocService` could render a GraphQL IDE rather than Armeria's default web console for GraphQL service.

GraphQL playground looks better but I also concern about the size of the packaged jar.
We need to find a good candidate by considering both usability and lightness.

### PR DESCRIPTION
**Pull request by heowc**
Motivation:

Trying to utilize `DocService` to provide a service like `GraphiQL`.

Modifications:

- Add `GraphqlDocServicePlugin`
    - Only provided by `POST` method
- Add debug page like `graphiql`
    - Add `graphql`
    - Add `codemirror`
    - Add `codemirror-graphql`
    - etc...
- Fix `DocService`
    - Apply auto decompress
    - Apply to serve compressed file  

Result:

- Closes #3706

### CODE REVIEW

**Comment by heowc** [comment]
Preview

https://user-images.githubusercontent.com/22594101/130785067-4907bfee-90db-43ec-a58d-c28a82ff9fb9.mov

**Comment by heowc** [comment]
By the way, the git history of `package-lock.json` is strange 🤔

**Comment by trustin** [comment]
@heowc What's your NPM version? You have to use NPM 6 (not 7).

**Comment by trustin** [comment]
@heowc The auto-completion capability looks really nice! How about lazy-loading codemirror to reduce the initial load time though? I had some good results with `Loadable` before, but you might want to do some research again on which lazy-loader is the best for this case.

**Comment by heowc** [comment]
> @heowc What's your NPM version? You have to use NPM 6 (not 7).

I found the following information.

https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion

The `lockfileVersion` applied to the current master branch is 2, and it seems to have been installed with npm 7. I install from that file to npm 6 the `lockfileVersion` is 1.

**Comment by heowc** [comment]
> How about lazy-loading codemirror to reduce the initial load time though? 

That's a good idea. Let's find out how to use it. 😎

**Comment by trustin** [comment]
> The lockfileVersion applied to the current master branch is 2, and it seems to have been installed with npm 7. I install from that file to npm 6 the lockfileVersion is 1.

@ikhoon Could you double check if your NPM version is 6? https://github.com/line/armeria/commit/b07cc7c9054d70b7debb1e4e1d29d994198bcd3c#diff-9ffb38058f2d97ce7a1218b13e7e7a14395ede90adb30d3e54f73c7de6e9a6a3

**Comment by ikhoon** [comment]
> > The lockfileVersion applied to the current master branch is 2, and it seems to have been installed with npm 7. I install from that file to npm 6 the lockfileVersion is 1.
> 
> @ikhoon Could you double check if your NPM version is 6? [b07cc7c#diff-9ffb38058f2d97ce7a1218b13e7e7a14395ede90adb30d3e54f73c7de6e9a6a3](https://github.com/line/armeria/commit/b07cc7c9054d70b7debb1e4e1d29d994198bcd3c#diff-9ffb38058f2d97ce7a1218b13e7e7a14395ede90adb30d3e54f73c7de6e9a6a3)

NPM 7 version was installed. 😆 But could install NPM v6.14.15 version with https://github.com/nvm-sh/nvm by installing NodeJS v14.18.0.
The lockfileVersion is 1 and the changed lines are `802 insertions(+), 540 deletions(-)`.

**Comment by heowc** [comment]
> The lockfileVersion is 1 and the changed lines are 802 insertions(+), 540 deletions(-).

If I install with NPM 6 from an existing file, can I get the above result? It might be something I'm not familiar with, but I think it's a bit odd. I tried installing with NPM 6 from the master branch, but still a lot of changes.

https://github.com/line/armeria/compare/master...heowc:apply-npm6

In the `site` module, `lockfileVersion` is 1, and as a result of installing the same, there is no change.

**Comment by heowc** [comment]
> How about lazy-loading codemirror to reduce the initial load time though?

I tried applying loadable to QueryEditor component (with codemirror) and got the following output.

스크린샷 2021-09-29 오전 10 39 44

스크린샷 2021-09-29 오전 10 44 51

**Comment by heowc** [comment]
https://github.com/line/armeria/pull/3807#issuecomment-929744279

Can I ignore this change?? 🤔 If it's a problem, I'll send a another PR.

**Comment by trustin** [comment]
> The captured image is what it shows until after I select the GraphqlService. Therefore, there is a gap between the sections marked on Waterfall. Is this early? :thinking: 

Ah, I see. Thanks for the explanation. We don't have the size increase in `main.js` now, right?

**Comment by heowc** [comment]
>

Yes. Because it uses compressed js, it is similar to the previous size or slightly reduced.

**Comment by trustin** [comment]
Awesome. I looks like we're going into the right direction. Please feel free to let us know when you think it's not WIP anymore.

**Comment by heowc** [comment]
> Awesome. I looks like we're going into the right direction. Please feel free to let us know when you think it's not WIP anymore.

I've been neglecting this PR for quite some time. 🤣 After a simple task, I will create a new PR.

**Pull request closed without merging**
