### PR TITLE
Rename `armeria-testing-junit` module to `armeria-junit5`

### LINKED ISSUE #2677: Refine module structure
I want to discuss:
- Putting related modules into one directory. For example:
  - `rxjava2` and `rxjava3` under `rxjava` directory. (`thrift` and `dropwizard` as well)
  - service discovery modules under `discovery` directory.
- Changing the name of ZooKeeper artifact from `armeria-zookeeper` to `armeria-zookeeper-discovery`

Currently, I'm implementing service discovery using Eureka.
While I'm working on it, I was wondering if we need a separate directory for discovery because the number of discovery modules might get increased.
We are going to have at least three different discovery in the near future:
- Consul
- Eureka
- ZooKeeper

If we have them all under the `discovery` directory, it will be a little better to maintain those.
For the other modules, we have all Spring modules in `spring` directory.
But we didn't for others such as rxjava, thrift and dropwizard. I was wondering if we need to do the same approach. (rxjava tends to be grown #2676)

For the second, the name of `armeria-zookeeper` is a little vague, because ZooKeeper can be used in various ways, unlike Eureka which is just for service discovery.

### PR DESCRIPTION
**Pull request by minwoox**
Motivations:
We have decided to change module names. See https://github.com/line/armeria/issues/2677#issuecomment-618785096

Modifications:
- Rename `armeria-testing-junit` to `armeria-junit5`
- Rename `armeria-testing-junit4` to `armeria-junit4`
- Move all 3 classes in `armeria-testing-common` to `armeria-junit5` and `armeria-junit4`.

Result:
- Close #2677
- You now have to use `armeria-junit5` instead of `armeria-testing-junit`
- You now have to use `armeria-junit4` instead of `armeria-testing-junit4`
- `armeria-testing-common` is gone.

### CODE REVIEW

**Comment by anuraaga** [comment]
Why not keep `armeria-testing-common`? Or alternatively just copy in the source into each of `junit4` and `junit5`? IMO it's more than weird that core has testing classes, it breaks an important principal of code structure where testing classes shouldn't be mixed with business logic ever.

**Comment by minwoox** [comment]
> Or alternatively just copy in the source into each of junit4 and junit5?

Yeah, let me put them in `junit5` and copy into gen-src using Gradle. 😄

**Comment by minwoox** [comment]
@anuraaga Fixed. PTAL. 😉

**Comment by trustin** [comment]
@minwoox Could you update the PR description?

**Comment by trustin** [comment]
Ah, could you rename `copyFiles` to `generateSources` so that `./gradlew generateSources` generates everything to make IDE happy?

**Comment by minwoox** [comment]
@trustin Done. 😄

**Pull request merged**
