### PR TITLE
Use `-deststoretype pkcs12` to remove warning

### PR DESCRIPTION
**Pull request by imasahiro**
Motivation:

When I follow https://armeria.dev/docs/advanced-saml/#configuring-your-server-as-a-service-provider, it shows following warnings which suggest to specify `-deststoretype pkcs12`.
```
JKSキーストアは独自の形式を使用しています。"keytool -importkeystore -srckeystore a.jks -destkeystore a.jks -deststoretype pkcs12"を使用する業界標準の形式であるPKCS12に移行することをお薦めします。
```

Modifications:

- Add -deststoretype pkcs12 option to example

Result:
- Less warns at example

### CODE REVIEW

**Comment by imasahiro** [comment]
I cannot remember how we sync between this repo and https://github.com/line/armeria-examples but... is it ok to put PR to here? or need to send to https://github.com/line/armeria-examples instead?

**Comment by minwoox** [comment]
> I cannot remember how we sync between this repo and [line/armeria-examples](https://github.com/line/armeria-examples) but... is it ok to put PR to here? or need to send to [line/armeria-examples](https://github.com/line/armeria-examples) instead?

You don't need to do anything. 😉 
The repository is updated when we release a new version. 😉

**Comment by minwoox** [comment]
For reference: https://www.baeldung.com/java-keystore-truststore-difference

**Review by minwoox — APPROVED** [review]
Thanks, @imasahiro!

**Review by jrhee17 — APPROVED** [review]
Pushed a small commit which also updates the site. Thanks @imasahiro 🙇 👍 🙇

**Review by ikhoon — APPROVED** [review]
Thanks, @imasahiro! 🙇‍♂️

**Pull request merged**
