### PR TITLE
Remove usages of jetty alpn

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

ALPN APIs have been backported since OpenJDK 8u252 (2020.04.15). Since development environments are relatively easier to upgrade, I propose that we remove ALPN usages in our gradle scripts.

Once this PR is approved, I'll upload a similar change in the upstream repo.

Modifications:

- Remove all usages of Jetty ALPN agents in our gradle scripts.

Result:

- Cleaner gradle code
- Easier gradle task input caching since an absolute path to the agent jar isn't used.

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks!

**Review by trustin — APPROVED** [review]
Thanks a lot for cleaning this up, @jrhee17 ! :bow:

**Review by minwoox — APPROVED** [review]
Thanks!

**Comment by minwoox** [comment]
Do you have a plan to commit all those Gradle changes to line/gradle-scripts?
Let me know when it's done so that we can also use it for Central Dogma. 😉

**Comment by jrhee17** [comment]
Added a PR I forgot about. The other changes have already been merged in
https://github.com/line/gradle-scripts/pull/157

**Comment by minwoox** [comment]
Oops, didn't notice that. Thanks!

**Comment by minwoox** [comment]
Oops, I found out that we also need to fix here:
https://github.com/line/armeria/blob/6d2790e80bd3858ed63450d6ff31099da4fa809c/core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java#L2033-L2040

**Comment by jrhee17** [comment]
> Oops, I found out that we also need to fix here:

I failed to understand 😅    How do you propose we fix the following line? The original intention was that
1. Developers using `gradle-scripts` now don't need jetty ALPN
2. Armeria users may still need jetty ALPN

**Comment by minwoox** [comment]
Oops, never mind the comment. 😓 I misread the code.

**Pull request merged**
