### PR TITLE
Allow SettableHealthChecker to have chained invocation.

### PR DESCRIPTION
**Pull request by anuraaga**
Currently, it can sometimes be inconvenient that a `SettableHealthChecker` can't have `setHealthy` called fluently. This is mainly because the default is `false` though - it might be good to consider whether the default should be `true`, in which case this change becomes less useful.

### CODE REVIEW

**Comment by hyangtack** [comment]
> This is mainly because the default is false though - it might be good to consider whether the default should be true, in which case this change becomes less useful.
@anuraaga How about adding a constructor which can set the initial `isHealthy` value as well?

**Comment by trustin** [comment]
How about changing the default value to `true`, adding a constructor with an initial value and changing the return type of `setHealthy()`?

**Comment by trustin** [comment]
@anuraaga Gentle ping. Hoping to release 0.84.0 today. :wink:

**Comment by trustin** [comment]
Could you fix the test failures? :wink:

**Comment by anuraaga** [comment]
Doh! Sorry will fix em up tomorrow

**Comment by anuraaga** [comment]
Travis seems to be having trouble downloading openjdk

**Comment by trustin** [comment]
Thanks, @anuraaga !

**Pull request merged**
