### PR TITLE
Support Thrift 0.16

### PR DESCRIPTION
**Pull request by Jimexist**
- Added `:thrift0.16` module, copying from 0.15
- Updated code references to point to 0.16

### CODE REVIEW

**Comment by ikhoon** [comment]
Thanks for upgrading Thrift version. We also update Thrift binary together to https://github.com/line/armeria/tree/c71ff7f0f3f4ca94c73d085eee75d318bcb15209/gradle/scripts/lib/thrift.

Unfortunately, Thrift does not deploy binary of new version for Linux. You need to manually compile the source code. If you have trouble building the source code or don't have time for it, please feel free to let us know.

**Comment by Jimexist** [comment]
> Thanks for upgrading Thrift version. We also update Thrift binary together to https://github.com/line/armeria/tree/c71ff7f0f3f4ca94c73d085eee75d318bcb15209/gradle/scripts/lib/thrift.
> 
> Unfortunately, Thrift does not deploy binary of new version for Linux. You need to manually compile the source code. If you have trouble building the source code or don't have time for it, please feel free to let us know.

thanks for the suggestion.

i think [homebrew formula][1] will have bottled binary version covering most of the arch, so i'll wait for the result there

[1]: https://github.com/Homebrew/homebrew-core/pull/95203/files

**Comment by ikhoon** [comment]
I realized that we need to build Thrift binaries in a legacy CentOS to provide backward compatibility for old Linux operating systems.
So you don't need to care about the new Thrift binaries. 
We are going to add the new one if this PR is merged.

**Comment by minwoox** [comment]
> So you don't need to care about the new Thrift binaries.
We are going to add the new one if this PR is merged.

Yeah, let us add the binaries. BTW are you using Armeria with Thrift in production? @Jimexist

**Comment by Jimexist** [comment]
> I realized that we need to build Thrift binaries in a legacy CentOS to provide backward compatibility for old Linux operating systems. So you don't need to care about the new Thrift binaries. We are going to add the new one if this PR is merged.

yes i was going to ask why without adding the binary the CI could pass: it's either it's not used in CI or not really needed by production

**Comment by Jimexist** [comment]
> > So you don't need to care about the new Thrift binaries.
> > We are going to add the new one if this PR is merged.
> 
> Yeah, let us add the binaries. BTW are you using Armeria with Thrift in production? @Jimexist

not in production yet but we are evaluating this :-)

**Comment by minwoox** [comment]
> not in production yet but we are evaluating this :-)

That sounds awesome. 😆 Please let us know if you find any trouble while evaluating our project.

**Comment by ikhoon** [comment]
> yes i was going to ask why without adding the binary the CI could pass:

Because `thrift.0.16` did not override the default thrift binary version. So thrift 0.15 binary is used to build `thrift0.16` module.
https://github.com/line/armeria/blob/5bb25a14c7d61e4e9f7e9f938c9300f042be35db/thrift0.13/build.gradle#L24-L27

**Comment by trustin** [comment]
We've just pushed the Thrift 0.16 compiler binary to master. Could you update `thrift0.15/build.gradle` as well? (See `thrift0.14/build.gradle` as a reference)

**Review by trustin — APPROVED** [review]
Thanks, @Jimexist 🙇

**Review by jrhee17 — APPROVED** [review]
Thanks @Jimexist ! LGTM as long as the CI passes 🙇 👍 🚀

**Review by ikhoon — APPROVED** [review]
Thanks a lot, @Jimexist! 🚀

**Pull request merged**
