### PR TITLE
Increase `yarn` network timeout to 10 minutes

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

Our CI keeps failing during `yarn install`, which may be due to network
timeout between NPM registry and CI agents, although it's not 100% certain.

Modifications:

- Specify `--network-timeout 600000` option

Result:

Hopefully more stable build

### CODE REVIEW

**Comment by trustin** [comment]
Increasing timeout did not work. Trying `--mutex network` option just in case: https://github.com/yarnpkg/yarn/issues/7212#issuecomment-598889512

**Comment by trustin** [comment]
Hmm.. I start to feel like switching to npm. Is yarn any better than npm in our use case, @anuraaga?

**Comment by anuraaga** [comment]
I've noticed quite better performance from yarn 2 lately, and since it's developed maybe is more stable, should we try upgrading? It has a cool new mode that doesn't create a huge folder of folders in your working dir, optionally can be checked in.

https://yarnpkg.com/features/pnp

**Comment by trustin** [comment]
Seems like yarn 2 is not a drop-in replacement of yarn 1. I see some issues potentially due to PnP:

- `eslint` takes forever.
- Build fails with module load errors:
  ```
  ERROR in multi react-hot-loader/patch ./src/index.tsx
  Module not found: Error: Can't resolve 'babel-loader' in '/home/trustin/Workspaces/armeria/docs-client'
   @ multi react-hot-loader/patch ./src/index.tsx main[1]

  ERROR in multi react-hot-loader/patch ./src/index.tsx
  Module not found: Error: Can't resolve 'react-hot-loader/patch' in '/home/trustin/Workspaces/armeria/docs-client'
   @ multi react-hot-loader/patch ./src/index.tsx main[0]
  ```

I have pushed a commit just in case you have a clue, @anuraaga.

**Comment by anuraaga** [comment]
Ah at least does need to be loose pnp mode I think

https://yarnpkg.com/features/pnp#pnp-loose-mode

**Comment by trustin** [comment]
Still not working :thinking:

**Comment by anuraaga** [comment]
I could get `docs-client:build` to work locally

- `yarnUpdate` to update the lockfile
- Replace `yarn` task with a new `yarnInstall`. Not sure why but default is always appending an empty string `""` to the args list which yarn 2 doesn't seem to like
- Ignore `.pnp.js` in `.eslintrc.js`

Didn't check other projects but hope this helps, let me know if you need more help

**Comment by anuraaga** [comment]
Hmm still file lock issue on CI. It's a bit unexpected to see the source in `/appveyor/projects` though, I thought appveyor clones to `/home/appveyor/projects`. Is there a chance that `/home/appveyor` is a shared folder in the BYoB setup?

```
➤ YN0001: │ Error: @babel/helper-compilation-targets@npm:7.9.6: Couldn't acquire a lock in a reasonable time (via /home/appveyor/.yarn/berry/cache/@babel-helper-compilation-targets-npm-7.9.6-0d60b1e50a-3.zip.flock)
    at s.lockPromise (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:10:106835)
    at async f.writeFileWithLock (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:92830)
    at async /appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:91686
    at async /appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:92865
    at async s.lockPromise (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:10:107015)
    at async f.writeFileWithLock (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:92830)
    at async B (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:91646)
    at async /appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:92392
    at async fetchPackageFromCache (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:42:92319)
    at async l.fetch (/appveyor/projects/armeria/site/.yarn/releases/yarn-berry.js:10:390811)
```

**Comment by trustin** [comment]
We don't share anything between builds. Each profile has its own docker container. The only shared directory is `/var/cache/appveyor` which is used for `rsync`'ing cache directories, which is accessed before/after the build.

**Comment by trustin** [comment]
IIRC, `/appveyor/projects` is the hard-coded location for Git cloning, so I guess it's not shared as well.

**Comment by anuraaga** [comment]
Ah noticed that in the `site` build both docs-client and site get built (is it intended? I thought site build should only be building the site). So one `yarn` times out on getting the lock while the other `yarn` seems to have the same stuck fetching behavior as before. 

Went ahead and tried overriding the registry to npmjs. If this doesn't work, I'd be surprised if the npm command does, but trying to switch would be the only remaining option I guess.

**Comment by trustin** [comment]
`site` task requires javadoc and that seems to trigger `docs-client`. Anyways, we could add something like `mustRunAfter` so that they do not run simultaneously. Let me take a closer look today. Thanks a lot for trying to help!

On the other hand, I'm not sure why `PROFILE=javaX` fails. They do not build `site` at all.

**Comment by anuraaga** [comment]
Yeah so I'm not optimistic tweaking Gradle will help :( Yarn does seem to be concurrent-aware, so I think site and docs-client are showing the same behavior of waiting forever to fetch, site just happens to give an error message too since while one of the projects is waiting forever the other one gives up on getting the lock.

**Comment by trustin** [comment]
Failed to fix the locking problem after some tries. Gatsby also doesn't seem to be PNP-ready unlike Yarn 2 web page advertises (or at least it's broken at the moment). Let me close this and send a PR that switches to NPM.

**Pull request closed without merging**
