### PR TITLE
allow for repeated method declarations

### PR DESCRIPTION
**Pull request by edgao**
Motivation:

When a Thrift service inherits from another service, armeria incorrectly sees the inherited methods as duplicated.

Modifications:

* Accept multiple declarations of the same method, making sure to always take the most specific declaration

Example error:
```
Exception in thread "main" java.lang.IllegalArgumentException: duplicate Thrift method name: cancel
	at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.checkDuplicateMethodName(ThriftServiceMetadata.java:196)
	at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:177)
	at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.lambda$init$1(ThriftServiceMetadata.java:94)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.init(ThriftServiceMetadata.java:93)
	at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.init(ThriftServiceMetadata.java:72)
	at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.<init>(ThriftServiceMetadata.java:60)
	at com.linecorp.armeria.server.thrift.ThriftServiceEntry.<init>(ThriftServiceEntry.java:49)
	at com.linecorp.armeria.internal.shaded.guava.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.linecorp.armeria.server.thrift.ThriftCallService.<init>(ThriftCallService.java:95)
	at com.linecorp.armeria.server.thrift.ThriftCallService.of(ThriftCallService.java:73)
	at com.linecorp.armeria.server.thrift.THttpService.ofFormats(THttpService.java:241)
	at com.linecorp.armeria.server.thrift.THttpService.ofFormats(THttpService.java:189)
	at com.liveramp.partner_stats_service.service.PartnerStatsServer.main(PartnerStatsServer.java:68)
```

### CODE REVIEW

**Comment by edgao** [comment]
actually lemme add a unit test too

**Comment by hyangtack** [comment]
@edgao Would you please take a look on the compile errors?

**Comment by trustin** [comment]
@edgao, could you fix the build failure?

**Comment by edgao** [comment]
Oops, sorry about that! I think this commit should fix.

**Comment by edgao** [comment]
@trustin @hyangtack build is now succeeding, ptal

**Comment by trustin** [comment]
Thanks a lot, @edgao!

**Pull request merged**
