### PR TITLE
Guess `ExchangeType` if it is not set in `RequestOptions`

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

`ExchangeType` is a hint for performance optimization. If no `RequestOptions` is set, it is inferred from the type of `HttpRequest`. However, a custom `RequestOptions` is set, `ExchangeType` is not inferred even if the `RequestOptions.exchangeType()` is null.

Modifications:

- Use `ExchangeType.RESPONSE_STREAMING` if `RequestOptions.exchangeType()` is null and `HttpRequest` is an instance of `FixedStreamMessage`.
- If none of the above conditions are met, the method defaults to returning ExchangeType.BIDI_STREAMING.

Result:

`ExchangeType` is guessed correctly even if `RequestOptions` is set.

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
Looks straightforward enough 👍  Thanks @ikhoon 🙇 👍 🙇

**Comment by jrhee17** [comment]
\+ Please check the lint failures 🙇

**Review by thachlp — APPROVED** [review]
Updated to modification: 
- If none of the above conditions are met, the method defaults to returning `ExchangeType.BIDI_STREAMING`.

Could you explain this default meaning?

**Comment by ikhoon** [comment]
Good question.
Armeria requests and responses are a stream that does not hold all messages. One variant is `FixedStreamMessage` which contains all objects at the creation time. Reactive stream processing for backpressure is not required for the unary message type.

Otherwise, we use a streaming `ExchangeType` to subscribe to the message one by one when a message is written to the wire. 

My answer may not be sufficient to explain Armeria's stream processors. If you want to know more about that, please let us know.

**Comment by thachlp** [comment]
> Good question. Armeria requests and responses are a stream that does not hold all messages. One variant is `FixedStreamMessage` which contains all objects at the creation time. Reactive stream processing for backpressure is not required for the unary message type.
> 
> Otherwise, we use a streaming `ExchangeType` to subscribe to the message one by one when a message is written to the wire.
> 
> My answer may not be sufficient to explain Armeria's stream processors. If you want to know more about that, please let us know.

Thanks for explaining to me 🙇
I just started learning Armeria :)

**Review by minwoox — APPROVED** [review]
Great, thanks!

**Pull request merged**
