### PR TITLE
Fix examples in server-service-registration.mdx

### PR DESCRIPTION
**Pull request by eisig**
fix  EurekaUpdatingListenerBuilder  sample code.

### CODE REVIEW

**Comment by trustin** [comment]
@eisig Thank you so much for your first contribution! :tada: Could you sign the ICLA first? Did you try Eureka service discovery test? What's your impression so far?

**Comment by eisig** [comment]
@trustin I am optimizing some old hessian projects. I plan to use armeria's multi-protocol support to add support beyond Hessian. But I haven't started doing this yet. I  am adding support for service discovery first,  the single jar dependency of armeria make  it safer and easier to change.

**Review by ikhoon — APPROVED** [review]
Oops... Thanks for catching them! @eisig 🙏

**Review by minwoox — APPROVED** [review]
Oops, thanks! 😄

**Review by trustin — APPROVED** [review]
:bow:

**Pull request merged**
