### PR TITLE
Fix `ktlintCheck` task

### LINKED ISSUE #3699: `noLint` option is not applied to `ktlintCheck` task
`ktlintCheck` is the task ktlint runs. I think github-action should ignore this task, but it doesn't work that way.

- https://github.com/line/armeria/runs/3056219351#step:6:405

Also, `ktlintCheck` is not running in lint jobs.

- https://github.com/line/armeria/runs/3056218928

What do you think?

### PR DESCRIPTION
**Pull request by heowc**
Motivation:

The task I mentioned has two problems. 
The task does not work under `lint` task. It also works when adding settings with `noLint`.

Modifications:

- Fix gradle script (`kotlin.gradle`)
- Remove unnecessary plugin dependencies

Result:

- Closes #3699

### CODE REVIEW

**Comment by heowc** [comment]
We can see that `ktlintCheck` task only in `lint`.

See https://github.com/line/armeria/runs/3084040469#step:4:247

**Review by minwoox — APPROVED** [review]
Thank you!
Could you also send this PR to https://github.com/line/gradle-scripts? 😄

**Comment by heowc** [comment]
> Thank you!
> Could you also send this PR to https://github.com/line/gradle-scripts? 😄

Yes! :)

**Review by trustin — APPROVED** [review]
Thanks, @heowc!

**Review by ikhoon — APPROVED** [review]
Thanks! @heowc

**Pull request merged**
