### PR TITLE
Fix a deadlock when running JaCoCo task

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Explain why you're making this change and what problem you're trying to solve.

Modifications:

- List the modifications you've made in detail.

Result:

- Closes #<GitHub issue number>. (If this resolves the issue.)
- Describe the consequences that a user will face after this PR is merged.

### CODE REVIEW

**Comment by jrhee17** [comment]
Happy if this works, but didn't work when I tried this 😅 

https://github.com/jrhee17/armeria/commit/58d4ab9e839364e90d7806b3cee4e9ca33db469d
https://github.com/jrhee17/armeria/actions/runs/5464882513/jobs/9947526536

**Comment by ikhoon** [comment]
Oops... I didn't know you already tried it. 😅

**Comment by ikhoon** [comment]
The build on macOS has passed. Hmm... is there a hidden bug on `io.netty:netty-transport-native-kqueue`? 🤔

**Comment by ikhoon** [comment]
`io.netty:netty-transport-native-kqueue` worked well when Unix domain socket tests were excluded.

**Comment by ikhoon** [comment]
The build ran on [macos-11](https://github.com/actions/runner-images/blob/macOS-11/20230709.1/images/macos/macos-11-Readme.md) has passed the CI tests.
It seems some new changes on macos-12 are incompatible with kqueue + unix domain sockets.

**Comment by ikhoon** [comment]
The root cause of the build failure of macOS turned out to be https://github.com/netty/netty/pull/13503
These comments and commit history do not help to understand the build error issue.

Let me close this and create a new PR to fix the failure.

**Comment by minwoox** [comment]
Thanks a lot for your investigation. 🙇

**Pull request closed without merging**
