### PR TITLE
Use JDK 17 by default

### PR DESCRIPTION
**Pull request by trustin**
- Use JDK 17 by default
- Remove JDK 15 builds from the GitHub Actions workflow

### CODE REVIEW

**Comment by trustin** [comment]
Looks like the build failed with:

```
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil
```

**Comment by trustin** [comment]
Looks like we need to wait for a new JMH version with Java 17 support:
```
> Task :benchmarks:compileJmhKotlin FAILED
'compileJmhJava' task (current target is 1.8) and 'compileJmhKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
e: Unknown JVM target version: 17
Supported versions: 1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16
```

**Comment by anuraaga** [comment]
@trustin Since the default is "1.8" not sure why it would be needed but something like this would probably fix it

https://kotlinlang.org/docs/gradle.html#attributes-specific-to-jvm

```
tasks {
  withType(KotlinCompile) {
    jvmTarget = "1.8"
  }
}
```

**Comment by ikhoon** [comment]
This PR is ready to review. PTAL. 🙇‍♂️

**Comment by trustin** [comment]
Only if the build passes? :smile:

**Comment by ikhoon** [comment]
> Only if the build passes? 😄

Oops… It passed in locally. 😱

**Comment by trustin** [comment]
Thanks for taking this PR over by the way. :+1: :bow:

**Comment by ikhoon** [comment]
Ah, shading. Luckily, A new version of Proguard that supports Java 17 has been released a few hours ago.
https://github.com/Guardsquare/proguard/releases/tag/v7.2.0

**Comment by trustin** [comment]
`DocumentationProcessorTest` fails on JDK 16. How about just removing JDK 16 from our builds given it's not even an LTS release?

**Comment by ikhoon** [comment]
I just realized `DocumentationProcessorTest` depends on JDK's `JavaCompiler` but JRE 16 is used to run the tests.
After applying [`d7e2b49` (#3837)](https://github.com/line/armeria/pull/3837/commits/d7e2b49bdbe79072e08ea630d126904b791bb685), the failure has been fixed. 😆

**Review by jrhee17 — APPROVED** [review]
Nice! Thank you @ikhoon and @trustin ! ❤️ 💯 🥇

**Review by ikhoon — APPROVED** [review]
Thanks, @trustin!

**Review by trustin — COMMENTED** [review]
Thanks a lot, @ikhoon :bow:

**Review by minwoox — APPROVED** [review]
Thank you all! ❤️

**Pull request merged**
