### PR TITLE
Apply `@Nullable` to local variables

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
After we add `ElementType.TYPE_USE` to `@NonNullByDefault`, IntelliJ started to complain about nullability
which is `Expression ... might evaluate to null but is returned by the method declared as @NonNullByDefault`.
We use `@Nullable` for method parameters and return values to suppress that but not for local variables.

Modifications:
- Apply `@Nullable` to local variables.

Result:
- Less complain from IntelliJ

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
😭 😭 😭 

`final` was already a problem but I think this tips over the cliff for contributor experience. I doubt I would send a PR after this change.

Generally nullability tools like Nullaway or checker framework don't need this since if return types are annotated, local variable nullability is easily inferred. Perhaps IntelliJ is configured incorrectly, or the annotation can be tweaked somehow to not cause this problem? As far as I know IntelliJ also infers nullability where it can and shouldn't be complaining about this.

**Comment by minwoox** [comment]
Thanks, @anuraaga for the opinion. 😄 
Yeah, that's probably not a good idea to use `@Nullable` for the local variables.
I had a chat with other members about this after I've seen it [here](https://github.com/line/armeria/pull/3795/files#diff-884e5b4b6e7da86e94604ae1f82462392a4064ba7978106fe09fd2b92e072a7eR79) from our contributor.
Should we ask to remove it or not.

We introduced [ElementType.TYPE_USE](https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.11) for the better compatibility with Kotlin: https://github.com/line/armeria/pull/3558
That added `@Nonnull` to the local variables so after that IntelliJ has been complaining about it.

I have tried to suppress the warning using tweaking the configuration of IntelliJ but only the way I could do was just disabling `Constance conditions & exceptions` which was not a good idea because there are some other conditions that the configuration validates.
So I think we have three options for now.
- Adding `@Nullable` to local variables
- Removing `ElementType.TYPE_USE`.
- Ignoring the warning.

I'm not so sure about the option 2. @ikhoon might have a word for that. 😄

**Comment by anuraaga** [comment]
It seems like a bug in IntelliJ that the annotation seems to cause nullability inferrence to just get turned off. Probably good to report it.

An alternative workaround to the bug instead of adding Nullable everywhere could be to add NonNull to the places it helps (I guess only when returning something like a `List<Foo>`. It should be lower impact and provide the same result in Kotlin I guess.

**Comment by minwoox** [comment]
> could be to add NonNull to the places it helps (I guess only when returning something like a List<Foo>

You mean removing `ElementType.TYPE_USE` from `NonNullByDefault` and add `NonNull` to the places?
Yeah, that could be a good option too.

**Comment by ikhoon** [comment]
> I guess only when returning something like a List<Foo>

I believe Armeria always returns a `List` that contains not-null values. I think it is acceptable.
However, in additional to `List`, Armeria API uses a lot of `CompletableFuture<SomeThinig>`, 
`Function<ShouldNot, ReturnNull>`, `Consumer<Bar>` whose nullabilities rather depend on the context.
Maybe most APIs are `@Nonnull` and 10% ~ 20% are nullable.

> You mean removing ElementType.TYPE_USE from NonNullByDefault and adding NonNull to the places?

Therefore, isn't it better to make `TYPE_USE` non-null by default?
I don't want to put `@NonNull` to most `CompletableFuture`'s type parameter. 😆

**Comment by anuraaga** [comment]
The jetbrains behavior, both kotlin and intellij seem problematic. Kotlin more so, checker framework invented the concept of null types in Java, it's too bad their annotations aren't supported - they can compose different null ability for different targets.

I'd say while it is a bit weird to add nonnull in places instead of the usual practice if nullable. But it's still the same as always - reason out the nullability of parameters and returns. Extending this to local vars is a huge explosion that will kill the readability and writability of the code.

Kotlin 1.5 is pretty new - the UX has problems as we've found. I don't their intention is to introduce significant regressions in writing libraries in Java to support the kotlin experience. So need to work with jetbrains on improving this.

**Comment by minwoox** [comment]
Yeah, the best way to solve this issue could be disabling the warning for local variables.
Filed an issue for that. 😉 
https://youtrack.jetbrains.com/issue/IDEA-277519

**Comment by minwoox** [comment]
It seems like we can disable the warning from NEXT 2021.3 EAP 2.
So let me close this PR. 😉

**Pull request closed without merging**
