### PR TITLE
Add a benchmark for plaintext

### PR DESCRIPTION
**Pull request by hexoul**
Motivation:
- Investigate the bottleneck or time-consuming job to improve the performance with data
- Increase [the rank in TechEmpower](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext&l=zik0vz-sf)

Modifications:
- Add a benchmark for plaintext

Result:
- 
- flame graph

### CODE REVIEW

**Comment by trustin** [comment]
Awesome initiative, @hexoul! I believe sky is the limit - we didn't try to optimize hard yet :wink:

**Review by trustin — APPROVED** [review]
Thanks, @hexoul! Did you find anything useful from a profiler?

**Comment by hexoul** [comment]
I didn't review the whole flow yet. However, as `Http1ObjectEncoder` occupies about 30% of time in benchmarking, I first have been trying to find a room to improve for that. I guess, it could be stream caching. https://camel.apache.org/manual/latest/stream-caching.html

**Comment by trustin** [comment]
Yeah, we could handle a request or a response with zero or one `HttpData` specially.

**Review by ikhoon — APPROVED** [review]
Thanks! @hexoul

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Pull request merged**
