### PR TITLE
Reorganize project to support multi-module project

### PR DESCRIPTION
**Pull request by imasahiro**
Modifications:
 * Migrate to gradle
 * Create armeria and site directory .

https://github.com/line/armeria/issues/65

### CODE REVIEW

**Comment by trustin** [comment]
Seems like you just create a directory and move everything there? Is this a work in progress?

**Comment by imasahiro** [comment]
Sorry for my late reply.
I planned to split armeria to armeria-common, armeria-server, armeria-client (you can see directory the layout from https://github.com/imasahiro/armeria/blob/multi-project/multi-project.sh ) but 
the plan was stacked because some tests (for example, GracefulShutdownIntegrationTest) use both server and client code and I don't have any idea for fixing this. So I just created `armeria` dir and move java/thrift code.
You can check gradle related code in following links.
https://github.com/imasahiro/armeria/blob/b3c4baa2f3d9d1281fc36a317a7eb795378a613b/build.gradle
https://github.com/line/armeria/pull/185/files#diff-9c384dd4cc870a45253a8e40fc29ab23

**Comment by anuraaga** [comment]
I think to allow splitting into three modules, you would want to add a fourth, armeria-testing module which contains shared test code (similar to netty-testsuite, though the word testsuite seems too specific).

**Comment by trustin** [comment]
I'm not sure if it's necessary to split Armeria into common/client/server given that client and server are often used together by a user. Before splitting Armeria into multiple modules, could we just update the project layout so that we can add a new module later?

**Comment by trustin** [comment]
Related conversation:
https://github.com/line/armeria/pull/201#discussion_r70602114

**Comment by imasahiro** [comment]
Close because https://github.com/line/armeria/pull/294 cover this PR.

**Pull request closed without merging**
