### PR TITLE
Make `ClientFactory` a part of `ClientOptions`

### LINKED ISSUE #1913: Disparity between HttpHealthCheckedEndpoint and HttpClient can be confusing.
This might be hard to solve, but we found some difficulties using `HttpHealthCheckedEndpointGroup` because it is separate from `HttpClient`. We configured the `HttpClient` with https, and decorators, but we also had to do the duplicate configuration on the `HttpHealthCheckedEndpointGroup` too, which we forgot at first. As it's redundant, it would be nice if this only had to be set once.

### LINKED ISSUE #2384: Make `ClientFactory` a part of `ClientOptions`.
When creating a new client derived from an existing client, a user can write the following code:

```java
WebClient client = WebClient.builder(...)...build();
WebClient derived = WebClient.builder(client.scheme().sessionProtocol(),
                                      client.endpointGroup())
                             .path(client.absolutePathRef())
                             .factory(client.factory())
                             .options(client.options())
                             .build();
```

Perhaps we could make `ClientFactory` a part of `ClientOptions`, so that a user doesn't have to specify it manually?

I don't think we have do this for `path` though, because it's part of the endpoint URI.

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

When creating a new client derived from an existing client, a user can
write the following code:

```java
WebClient client = WebClient.builder(...)...build();
WebClient derived =
    WebClient.builder(client.scheme().sessionProtocol(),
                      client.endpointGroup())
             .path(client.absolutePathRef())
             .factory(client.factory())
             .options(client.options())
             .build();
```

We could make `ClientFactory` a part of `ClientOptions`, so that a user
doesn't have to specify it manually:

```java
WebClient derived =
    WebClient.builder(client.scheme().sessionProtocol(),
                      client.endpointGroup())
             .path(client.absolutePathRef())
             .options(client.options())
             .build();
```

Modifications:

- Add `ClientOption.FACTORY`.
- Add `AbstractClientOptionsBuilder.factory(ClientFactory)`
  - Remove the `factory(ClientFactory)` methods in the subclasses
- (Breaking) `ClientBuilderParams.of()` does not require a
  `ClientFactory` anymore.
  - Hide `DefaultClientBuilderParams` from the public API
- (Deprecation) Deprecate `ClientBuilderParams.factory()`
- (Breaking) `DefaultClientRequestContext()` does not require a
  `ClientFactory` anymore.
- Clean up the client configuration in `AbstractHealthCheckedEndpointGroupBuilder`.
  - (Breaking) `HealthCheckerContext.clientConfigurator()` and
    `clientFactory()` has been replaced with `clientOptions()`.
- Miscellaneous:
  - Remove unused fields in `HealthCheckedEndpointGroupTest`

Result:

- Fixes #1913
- Fixes #2384
- `ClientBuilder.options(ClientOptions)` now sets `ClientFactory` as
  well as other options, which is more convenient when building a
  derived client.
  - However, this may break the following code:
    ```java
    builder.factory(myFactory)
           .options(myOptions)
    ```
    .. because `myFactory` will be ignored and `myOptions.factory()`
    will be used instead.

### CODE REVIEW

**Comment by ikhoon** [comment]
> However, this may break the following code:
> ```
> builder.factory(myFactory)
>        .options(myOptions)
> .. because myFactory will be ignored and myOptions.factory()
> will be used instead.

Everything is fine except this point. Is there any change we notify to a user by 1) `throw Exception` or 2) Add a `@Deprecation`?

**Comment by trustin** [comment]
> Everything is fine except this point. Is there any chance we can notify a user by 1) `throw Exception` or 2) Add a `@Deprecation`?

This was already happening for other setters such as `requestTimeout()`. I think it's hard to tell if it's by intention or mistake..

**Comment by ikhoon** [comment]
> This was already happening for other setters such as requestTimeout(). I think it's hard to tell if it's by intention or mistake..

I see, then SGTM again! 😀

**Comment by trustin** [comment]
Thanks for reviewing!

**Pull request merged**
