### PR TITLE
Fix buffer leak on DNS query timeout

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

`DefaultDnsNameResolver` does not release the collected `DnsRecord`s
when it failed to complete a future with them, which can happen when a
DNS query has timed out already. (Thanks to @kojilin for finding out the
cause of the leak.)

Modifications:

- Release the collected `DnsRecord`s when failed to complete a future.
- Fix a bug where `ByteBufHttpData.touch()` hangs indefinitely.
- Fail the build when the test output contains `LEAK: `.

Result:

- No buffer leak on DNS query timeout.
- Build fails when there's a leak.

### CODE REVIEW

**Comment by trustin** [comment]
I can write a slow DNS server, but I'm not sure how I can check if the records are released. 🤔

**Comment by anuraaga** [comment]
@trustin Don't we have logging of leaked references on CI? It's probably fine if that triggers even if not natively asserted.

**Comment by kojilin** [comment]
Also curious about how to write test ByteBuf leak.    
Not sure the implementation of `promise.cancel(true)`,  does it have a possibility that DnsRecord is built but not calling the `operationComplete` here. Or even we call cancel, if the record is built and retain successfully, the complete of promise(`operationComplete` here) must be called with result.

**Comment by trustin** [comment]
> Not sure the implementation of `promise.cancel(true)`,  does it have a possibility that DnsRecord is built but not calling the `operationComplete` here. Or even we call cancel, if the record is built and retain successfully, the complete of promise(`operationComplete` here) must be called with result.(This is the cause this time?)

`promise.cancel()` will trigger `operationComplete()`, but we will have to release half-collected records. Let me tighten the release logic.

**Comment by trustin** [comment]
@anuraaga Yeah, let me write a test case with slow DNS server, and then send a follow-up PR that makes the build fail when a LEAK error message is logged.

**Comment by trustin** [comment]
> send a follow-up PR that makes the build fail when a LEAK error message is logged.

Done in this PR

**Comment by trustin** [comment]
Once this is merged and we fixes all leaks during the build process, I'll try to add a new build profile that runs the build with `-Pleak` option, although it might not be possible due to high memory usage.

**Comment by trustin** [comment]
@kojilin Let me merge this for now. Please feel free to let us know if you have more information about the leak.

**Pull request merged**
