### PR TITLE
Newsletter vol. 6

### PR DESCRIPTION
**Pull request by trustin**
Preview:
image

### CODE REVIEW

**Comment by trustin** [comment]
We could add a new section 'Who's using Armeria?' and add one or two new companies since the last newsletter. What do you think?

**Review by jrhee17 — APPROVED** [review]
Thanks @trustin ! 🙇 👍 🙇

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by ikhoon — APPROVED** [review]
Thanks!! 🙇‍♂️

**Pull request merged**
