### PR TITLE
Upgrade to brotli4j 1.9.0

### PR DESCRIPTION
**Pull request by sullis**
Motivation:

brotli4j 1.9.0 is the latest release. 

Release notes: https://github.com/hyperxpro/Brotli4j/releases/tag/v1.9.0

Modifications:

- modified version number in dependencies.toml 

Result:

- Brotli test suite passes

### CODE REVIEW

**Comment by sullis** [comment]
fyi:  @hyperxpro

**Comment by minwoox** [comment]
Hi! Thanks for the PR.
Because we've recently released 1.21.0, we are going to release the next version which contains this change in mid-January.

**Review by ikhoon — APPROVED** [review]
Thanks, @sullis! 🙇‍♂️

**Review by hyperxpro — APPROVED** [review]
Looks good. :)

**Review by jrhee17 — APPROVED** [review]
Thanks @sullis ! 👍

**Pull request merged**
