### PR TITLE
Fix flaky `PrometheusMetricExposureTest`

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

As `AutoConfiguration.imports` in the test resource of `spring:boot3-actuator-autoconfigure` isn't copied to `spring:boot2-actuator-autoconfigure`, `PrometheusMetricExposureTest` didn't restart a server when it fails to start.

Related issue: #4941

Modifications:

- Copy `AutoConfiguration.imports` file in `boot3-autoconfigure/src/test/...' to `spring:boot2-actuator-autoconfigure`

Result:

Stabilize the CI build state

### CODE REVIEW

**Comment by ikhoon** [comment]
I am fixing the Gradle task dependency problem.

**Comment by ikhoon** [comment]
I found it difficult to depend on the `generateTestSources` task that is dynamically added while a product is initialized. The configuration is a single file and is not frequently changed so I copy `AutoConfiguration.imports` for simplicity.

**Comment by jrhee17** [comment]
> 
I found it difficult to depend on the generateTestSources task that is dynamically added while a product is initialized. The test configuration contains a single file and is not frequently changed, so I copied AutoConfiguration.imports for simplicity.

So is my understanding correct? 😅 
1. `:spring:boot3-autoconfigure` -> `:spring:boot3-actuator-autoconfigure` META-INF is copied
2. `:spring:boot3-actuator-autoconfigure` ->  `:spring:boot2-actuator-autoconfigure` META-INF is copied

Also, I'm wondering if `AutoConfiguration.imports` is not copied, does this mean the rest of the resources for `:spring:boot3-actuator-autoconfigure` are also not copied over to `:spring:boot2-actuator-autoconfigure`?

**Review by jrhee17 — APPROVED** [review]
Let me just go ahead and approve this pull request since I don't want to block release 😄

**Comment by ikhoon** [comment]
> Also, I'm wondering if AutoConfiguration.imports is not copied, does this mean the rest of the test resources for :spring:boot3-actuator-autoconfigure are also not copied over to :spring:boot2-actuator-autoconfigure?
(i.e. test/resources/config/application-*.yml)

All resources in `:spring:boot3-actuator-autoconfigure/test/resources` are used to build `:spring:boot2-actuator-autoconfigure`.
https://github.com/line/armeria/blob/e15c7b7809db6d77c6798c237707e942fceb51bb/spring/boot2-actuator-autoconfigure/build.gradle#L31
However, `AutoConfiguration.imports` copied from `:spring:boot3-autoconfigure`'s test resources  is located in `:spring:boot3-actuator-autoconfigure/gen-src/test/resources`. 

I wanted to apply the line with the following but failed because `boot3Actuator:generateTestSources` isn't accessible when initializing `:spring:boot2-autoconfigure`
```gradle
tasks.processTestResources.from "${boot3ActuatorProjectDir}/src/test/resources",
    "${boot3ActuatorProjectDir}/gen-src/test/resources"

tasks.processTestResources.dependsOn(project(":spring:$boot3Actuator").tasks.generateTestSources)
```

**Review by minwoox — APPROVED** [review]
Thanks!

**Pull request merged**
