### PR TITLE
Use the default settings for `Logging{Client,Service}`'s default fact…

### LINKED ISSUE #2696: Logging decorator factories should match semantics of empty builder
We deviated the behavior of the factories and builders a long time ago to preserve backwards compatibility of factories before we added the builders, but at the time we figured the better default for successful requests is `TRACE` to reduce log spam. So we should change the factory finally to just call `builder().build()` to reduce confusion of the defaults. This would mean either the factory's behavior changes to TRACE successful log entries, or the builder needs to be changed so successful log entries are INFO.

### PR DESCRIPTION
**Pull request by trustin**
…ory methods

Motivation:

So far, `Logging{Client,Service}.newDecorator()` had different settings
than `Logging{Client,Service}.builder().newDecorator()` due to backward
compatibility. It's time to change this in favor of consistency.

Modifications:

- Change the default logging level for successful requests and responses
  from `TRACE` to `DEBUG`.
- Change `Logging{Client,Service}.newDecorator()` to use its builder's
  default settings.
  - `DEBUG` level logging for successful requests and responses.
  - `WARN` level logging for failed requests and responses`.

Result:

- Consistency
- Fixes #2696
- (Breaking) The default logging level for successful requests and response
  has been changed:
  - `INFO` to `DEBUG` for `Logging{Client,Service}.newDecorator()`
  - `TRACE` to `DEBUG` for `Logging{Client,Service}Builder`

### CODE REVIEW

**Comment by trustin** [comment]
By the way, is `TRACE` level the right default for successful requests and responses? I was rather expecting `DEBUG`. Do you remember why we lowered to `TRACE`? /cc @imasahiro @kojilin @anuraaga

**Comment by minwoox** [comment]
I don't remember but `DEBUG` is fine with me.

**Comment by ikhoon** [comment]
Actually, I'm leaning towards `INFO`.😆 Because users can easily turn it off using logging framewrok xml configuration.

**Comment by ikhoon** [comment]
Related work: The default log level of Spring's CommonsRequestLoggingFilter is `DEBUG`.
https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/filter/CommonsRequestLoggingFilter.java#L39

**Comment by trustin** [comment]
Let me change the default level from `TRACE` to `DEBUG` tomorrow. Please feel free to let me know if you have any concern.

**Pull request merged**
