### PR TITLE
Add code completion for armeria.ssl

### PR DESCRIPTION
**Pull request by hirakida**
We didn't have code completion for `armeria.ssl`, so I added it.

before
Screen Shot 2021-05-02 at 16 48 16

after
Screen Shot 2021-05-02 at 16 46 36

### CODE REVIEW

**Comment by ikhoon** [comment]
Awesome! Could we apply `NestedConfigurationProperty` to other nested property classes?

**Comment by hirakida** [comment]
As far as I know, it's okay not to add it to the inner classes.
It seems that it is okay to apply it only to `ssl`!
Screen Shot 2021-05-02 at 18 06 31

**Comment by ikhoon** [comment]
> As far as I know, it's okay not to add it to the inner classes.

Thanks for the education. Good to know that. 👍

**Review by ikhoon — APPROVED** [review]
Thanks! @hirakida

**Review by minwoox — APPROVED** [review]
Thanks! I didn't know about this annotation. 😄

**Review by trustin — APPROVED** [review]
Nice usability boost, @hirakida :bow:

**Pull request merged**
