### PR TITLE
Add favicon to DocService

### PR DESCRIPTION
**Pull request by Ta2Rim**
**Motivation**
To make DocService easier to identify

**Modifications**
add favicon

**Result**
before
image

after
image

### CODE REVIEW

**Comment by ikhoon** [comment]
> So the size of this favicon is 32, right?

That's a good idea. Could you add favicon for multiple devices?
https://realfavicongenerator.net/

**Comment by ikhoon** [comment]
Plus, could you add a favicon for our official documents too? 😉
https://line.github.io/armeria/

**Comment by anuraaga** [comment]
Let's use [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin) to generate the favicons at build time from a single image :)

Do we have an image source for generating the favicons anywhere? I guess a 512x512 or so PNG would be able to generate all the different image sizes.

**Comment by Ta2Rim** [comment]
> Let's use [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin) to generate the favicons at build time from a single image :)
> 
> Do we have an image source for generating the favicons anywhere? I guess a 512x512 or so PNG would be able to generate all the different image sizes.

Yes There's a large SVG icon file in `site` directory
I'll extract PNG file from it

**Comment by trustin** [comment]
Great. Please let us know once we switch to a bigger and better icon. :-)

**Comment by Ta2Rim** [comment]
I just found out @trustin created sphinx-maven-plugin.
That's cool!!

I add a line to conf.py, too.
Now it works both on official site and Doc service

**Comment by trustin** [comment]
@minwoox @ikhoon Care to check again?

**Comment by minwoox** [comment]
Still LGTM. Thanks! @Ta2Rim

**Comment by minwoox** [comment]
@Ta2Rim Could you tell me why you close this PR?

**Comment by Ta2Rim** [comment]
I don't know why it's closed... maybe I made mistakes 
I reopen it! sryy

**Comment by trustin** [comment]
Thank you, @Ta2Rim !

**Pull request merged**
