### PR TITLE
Update to guava 21.0

### PR DESCRIPTION
**Pull request by anuraaga**
- Replaces guava helper with upstream collectors
- Replaces gross spliterator stream creation with guava utility

There are probably more stream-related cleanups possible with 21.0, but these are big and easy ones.

### CODE REVIEW

**Comment by anuraaga** [comment]
@trustin PTAL

**Comment by trustin** [comment]
LGTM. Please fix the checkstyle error, then it's good to go. :-)

**Comment by anuraaga** [comment]
Yep just pushed with the style fix

**Comment by trustin** [comment]
Thanks a lot, @anuraaga ! Learned a little bit about new features of Guava. :-)

**Pull request merged**
