### PR TITLE
Changes ThrottlingStrategy.accept to boolean

### PR DESCRIPTION
**Pull request by jmostella**
Simplifies logic for ThrottlingService

Should solve: https://github.com/line/armeria/issues/996

### CODE REVIEW

**Comment by kojilin** [comment]
I replied at https://github.com/line/armeria/issues/996 . not sure if this is a good idea to just remove future for solving this issue.

**Comment by trustin** [comment]
A user may want to decide after consuming the request body?

**Comment by jmostella** [comment]
@trustin Understood, but in that case couldn't they create their own `DeferedRpcThrottlingService` (just as example).

Unless this is the common use-case.

**Comment by trustin** [comment]
Yeah, I'm fine with providing two variants. How about updating this PR that way?

**Comment by trustin** [comment]
@jmostella Discussion continuing at #996

**Comment by jmostella** [comment]
@trustin per discussion should I will close this PR? Since it doesn't directly solve the issue.

**Comment by trustin** [comment]
> @trustin per discussion should I will close this PR? Since it doesn't directly solve the issue.

I'm leaning toward @anuraaga 's suggestion. +1 for closing this PR.

**Pull request closed without merging**
