### PR TITLE
Fix flaky test `ContextCancellationTest`

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

Let me just remove the validation like @minwoox suggested

Modifications:

- Removed the validation on request context.

Result:

- https://github.com/line/armeria/issues/5868

### CODE REVIEW

**Comment by ikhoon** [comment]
The CI status is unstable. I will postpone the release process until this issue is fixed. 
https://github.com/line/armeria/actions/runs/10348301653/job/28640280474#step:11:1945
https://github.com/line/armeria/actions/runs/10348301653/job/28640279386#step:11:2068

**Comment by jrhee17** [comment]
> The CI status is unstable. I will postpone the release process until this issue is fixed.

Sorry about this, will fix ASAP

**Comment by ikhoon** [comment]
No worries. Take your time. 😉

**Comment by jrhee17** [comment]
Ready for review

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Review by ikhoon — APPROVED** [review]
🙇‍♂️🙇‍♂️

**Pull request merged**
