### PR TITLE
Fix incorrect assertions in MoreMetersTest

### PR DESCRIPTION
**Pull request by trustin**
It is possible that a summary or a timer is registered already before
running MoreMetersTest. If that's the case, `armeria.hdrHistogram.count`
will not be 0 unlike the assumptions in `MoreMetersTest`.

### CODE REVIEW

**Comment by trustin** [comment]
Thanks!

**Comment by leedohyun** [comment]
@trustin 
I frequently saw below failed log when I built the code on master branch.

`
MoreMetersTest.hdrHistogramMeters: FAILURE

com.linecorp.armeria.common.metric.MoreMetersTest > hdrHistogramMeters FAILED
    java.lang.AssertionError: 
    Expecting:
     <{"armeria.hdrHistogram.count#value"=11.0, "armeria.hdrHistogram.estimatedFootprint#value"=608256.0, "foo.bar#count"=0.0, "foo.bar#total"=0.0}>
    to contain:
     <[MapEntry[key="armeria.hdrHistogram.count#value", value=1.0]]>
    but could not find:
     <[MapEntry[key="armeria.hdrHistogram.count#value", value=1.0]]>
        at com.linecorp.armeria.common.metric.MoreMetersTest.hdrHistogramMeters(MoreMetersTest.java:44)
`

**Comment by trustin** [comment]
@leedohyun Does it happens from `shadedCoreTest`? Then please run `./gradlew clean` first. If not, please let me know.

**Comment by leedohyun** [comment]
@trustin 
I ran `./gradlew clean` and `./gradlew build` again.
But I saw same failed log.

MoreMetersTest.hdrHistogramMeters: FAILURE

com.linecorp.armeria.common.metric.MoreMetersTest > hdrHistogramMeters FAILED
    java.lang.AssertionError: 
    Expecting:
     <{"armeria.hdrHistogram.count#value"=11.0, "armeria.hdrHistogram.estimatedFootprint#value"=608256.0, "foo.bar#count"=0.0, "foo.bar#total"=0.0}>
    to contain:
     <[MapEntry[key="armeria.hdrHistogram.count#value", value=1.0]]>
    but could not find:
     <[MapEntry[key="armeria.hdrHistogram.count#value", value=1.0]]>
        at com.linecorp.armeria.common.metric.MoreMetersTest.hdrHistogramMeters(MoreMetersTest.java:44)
16:13:41.213 [Thread-4] DEBUG c.l.armeria.client.ClientFactory - Closing the default ClientFactory

600 tests completed, 1 failed

> Task :core:testNg
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:test'.
> There were failing tests. See the report at: file:///~~~/armeria/core/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 59s
133 actionable tasks: 126 executed, 7 up-to-date

**Comment by trustin** [comment]
I'm not sure. As you might already have noticed, we have removed `MoreMetersTest` at master. Perhaps your fork is out-of-date?

**Comment by leedohyun** [comment]
I'm so sorry. My fork is out-of-date.

**Pull request merged**
