### PR TITLE
Upgrade dependencies for 1.22.0

### PR DESCRIPTION
**Pull request by jrhee17**
- Brave 5.14.1 -> 5.15.0
- Dropwizard-metrics 4.2.13 -> 4.2.15
- GraphQL Kotlin 6.3.2 -> 6.3.5
- gRPC Java 1.49.1 -> 1.52.1
- Hibernate Validator 6.2.3.Final -> 6.2.5.Final
- Jackson 2.14.1 -> 2.14.2
- java-jwt 4.2.1 -> 4.2.2
- Kafka client 3.3.1 -> 3.4.0
- Kotlin 1.7.22 -> 1.8.10
- Micrometer 4.10.0 -> 4.11.0
- Netty 4.1.86.Final -> 4.1.87.Final
  - io_uring 0.0.16.Final -> 0.0.17.Final
- Protobuf 3.21.1 -> 3.21.7
- Resteasy 5.0.4.Final -> 5.0.5.Final
- RxJava3 3.1.5 -> 3.1.6
- Sangria 3.4.1 -> 3.5.0
- Scala3 3.2.0 -> 3.2.2
- ScalaPB 0.11.12 -> 0.11.13
- ScalaPB JSON 0.12.0 -> 0.12.1
- Spring 5.3.23 -> 5.3.25
- Spring Boot 2.7.4 -> 2.7.8
- Tomcat8 8.5.84 -> 8.5.85
- Tomcat9 9.0.70 -> 9.0.71

Build dependencies
- AssertJ 3.23.1 -> 3.24.2
- ErrorProne 2.16 -> 2.18.0
- Finagle 22.7.0 -> 22.12.0
- gax-grpc 2.20.1 -> 2.23.0
- Groovy 3.0.13 -> 3.0.14
- j2objc 1.3 -> 2.8
- json-unit 2.36.0 -> 2.36.1
- JUnit 5 5.9.1 -> 5.9.2
- ktlint-gradle-plugin 11.0.0 -> 11.1.0
- node-gradle-plugin 3.5.0 -> 3.5.1
- osdetector 1.7.1 -> 1.7.2
- Snappy 1.1.8.4 -> 1.1.9.1

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks, @jrhee17! 🙇‍♂️

**Review by minwoox — COMMENTED** [review]
Thanks! :smile:

**Review by minwoox — APPROVED** [review]
Forgot to click the Approve button. 😅

**Comment by nao0811ta** [comment]
@jrhee17 
`Micrometer 4.10.0 -> 4.11.0`
is not correct
that would be Mockito

**Comment by jrhee17** [comment]
Oops thanks @nao0811ta 😄   Will fix the PR description/release notes 🙏

**Pull request merged**
