### PR TITLE
Use CircuitBreaker.tryRequest() instead of deprecated canRequest() in doc and test

### PR DESCRIPTION
**Pull request by cirusthenter**
Motivation:

Fix docs and  tests to use a new method `CircuitBreaker.tryRequest()` instead of deprecated `CircuitBreaker.canRequest()`.

Modifications:

- Fixed a line in `site/src/pages/docs/client-circuit-breaker.mdx` to use a new method `CircuitBreaker.tryRequest()` instead of deprecated `CircuitBreaker.canRequest()`.
- Fixed `core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java` to use a new method `CircuitBreaker.tryRequest()` instead of deprecated `CircuitBreaker.canRequest()`.

Result:

- https://armeria.dev/docs/client-circuit-breaker/ will be updated to show an example of using a new method `CircuitBreaker.tryRequest()`.

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
Thanks a lot, @cirusthenter!
I noticed that the `canRequest` method is still being used in `NonBlockingCircuitBreakerTest`.
Could you please fix that as well?

**Comment by cirusthenter** [comment]
Thanks for your review. Fixed `NonBlockingCircuitBreakerTest` as well!

**Review by ikhoon — APPROVED** [review]
Thanks for cleaning up!

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Pull request merged**
