### PR TITLE
Updates to Brave 5.12.1

### PR DESCRIPTION
**Pull request by adriancole**
waiting on release

### CODE REVIEW

**Comment by trustin** [comment]
Hey, thanks a lot!

**Comment by adriancole** [comment]
should be synced to central now.. we'll see what appveyor thinks!

**Comment by adriancole** [comment]
*should* be good now

**Comment by trustin** [comment]
Not sure why, but build is failing since this is merged:

```
> Task :brave:shadedTest
BraveServiceIntegrationTest > spanHandlerSeesException_async FAILED
    java.lang.AssertionError: Span didn't finish
        at brave.test.http.ITHttpServer.spanHandlerSeesError(ITHttpServer.java:540)
        at brave.test.http.ITHttpServer.spanHandlerSeesException_async(ITHttpServer.java:516)
```

**Comment by adriancole** [comment]
@trustin 5.12.2 gives some more information in this case.. does PR also fail but only master? https://github.com/line/armeria/pull/2725

**Comment by adriancole** [comment]
actually the 5.12.2 isn't going to fix this.. some kind of span finished, yet the end hook didn't see the exception. sometimes this can happen if the http handler's end function is called twice..

```java
    ConcurrentLinkedDeque<Throwable> caughtThrowables = new ConcurrentLinkedDeque<>();
    httpTracing = HttpTracing.create(tracingBuilder(Sampler.ALWAYS_SAMPLE)
        .addSpanHandler(new SpanHandler() {
          @Override public boolean end(TraceContext context, MutableSpan span, Cause cause) {
            Throwable error = span.error();
            if (error != null) {
              caughtThrowables.add(error);
            } else {
              caughtThrowables.add(new RuntimeException("Unexpected additional call to end"));
            }
            return true;
          }
        })
        .build());
    init();

    httpStatusCodeTagMatchesResponse_onUncaughtException(path, ".*not ready");

    assertThat(caughtThrowables)
        .withFailMessage("Span didn't finish") << wrong message
        .isNotEmpty();
```

**Comment by adriancole** [comment]
I'm actually still struggling to make sense of this, as `httpStatusCodeTagMatchesResponse_onUncaughtException` proves a span had an error.. yet none made it to `caughtThrowables`. as end() is called when finished, this is indeed curious..

**Comment by adriancole** [comment]
@trustin 5.12.3 going out to hopefully solve the flake. flaking build is worth fixing.. sorry!

**Pull request merged**
