### PR TITLE
Ignore a flaky test until it's fixed

### LINKED ISSUE #530: Appveyor build flaky
I often notice Appveyor build takes forever, and has random failures due to timeouts (e.g., ClosedSessionException). I guess the containers aren't very powerful. If I remember correctly, we requested strong machines from Travis, maybe that'd be a possibility here. Otherwise, how about removing shaded tests from the windows build? I think it's very unlikely that there'd be a windows-only issue with shaded jars, and they add a lot of time / load to the build. I dunno why, but I feel like most flakes on both Travis and Appveyor happen during shaded tests (perhaps time-based throttling).

### PR DESCRIPTION
**Pull request by trustin**
- Closes #530

### CODE REVIEW

**Comment by trustin** [comment]
Will merge once build passes. /cc @anuraaga @hyangtack

**Comment by trustin** [comment]
Build failed with unrelated failure:

```
com.linecorp.armeria.client.grpc.GrpcClientTest > cancelAfterFirstResponse FAILED
    java.lang.AssertionError: 
    Expected size:<1> but was:<0> in:
    <[]>
        at com.linecorp.armeria.client.grpc.GrpcClientTest.cancelAfterFirstResponse(GrpcClientTest.java:376)
```

Will rerun.

**Comment by trustin** [comment]
@anuraaga Would you take a look into the failure?

**Comment by anuraaga** [comment]
@trustin Yeah I've tried adding a fix in #549

**Pull request merged**
