### PR TITLE
Fix a recursive update with a `ConcurrentHashMap` in `RefreshingAddre…

### LINKED ISSUE #3528: Infinity loop on cache miss in `RefreshingAddressResolver`
I found a CI build that never terminates. https://github.com/line/armeria/runs/2514847200?check_suite_focus=true#step:9:2280
```java
"Test worker" #11 prio=5 os_prio=0 tid=0x00007f92fca0b000 nid=0x59a8 runnable [0x00007f92db288000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1808)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2133)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.LocalManualCache.invalidate(LocalManualCache.java:140)
	at com.linecorp.armeria.client.RefreshingAddressResolver.lambda$loadingCache$2(RefreshingAddressResolver.java:102)
	at com.linecorp.armeria.client.RefreshingAddressResolver$$Lambda$792/148660771.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:848)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2168)
	at com.linecorp.armeria.client.RefreshingAddressResolver.loadingCache(RefreshingAddressResolver.java:96)
	at com.linecorp.armeria.client.RefreshingAddressResolver.lambda$doResolve$3(RefreshingAddressResolver.java:125)
	at com.linecorp.armeria.client.RefreshingAddressResolver$$Lambda$781/1038650699.apply(Unknown Source)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2375)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache$$Lambda$709/2070334342.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x00000000f7d769a0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2373)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2356)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.linecorp.armeria.internal.shaded.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.linecorp.armeria.client.RefreshingAddressResolver.doResolve(RefreshingAddressResolver.java:125)
	at com.linecorp.armeria.client.RefreshingAddressResolver.doResolve(RefreshingAddressResolver.java:53)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:103)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:51)
	at com.linecorp.armeria.internal.client.ClientUtil.pushAndExecute(ClientUtil.java:150)
	at com.linecorp.armeria.internal.client.ClientUtil.initContextAndExecuteWithFallback(ClientUtil.java:95)
	at com.linecorp.armeria.internal.client.ClientUtil.initContextAndExecuteWithFallback(ClientUtil.java:67)
	at com.linecorp.armeria.client.UserClient.execute(UserClient.java:167)
	at com.linecorp.armeria.client.DefaultWebClient.execute(DefaultWebClient.java:108)
	at com.linecorp.armeria.client.DefaultWebClient.execute(DefaultWebClient.java:81)
	at com.linecorp.armeria.client.WebClient.execute(WebClient.java:243)
```

That is caused by recursive calls of `ConcurrentHashMap.computeXXX()`.
The bug was reported and patched in Java 9. https://bugs.openjdk.java.net/browse/JDK-8074374
As a result of the patch, the infinity loop is removed, but it still raises `IllegalStateException: Recursive update`.
Anyway, we need to fundamentally fix this problem because the minimum Java version is 8 for Armeria.

The following example is a minimal reproducible example for this.
```java
final Cache<String, CompletableFuture<String>> cache = Caffeine.newBuilder()
                                                               .build();
@Test
void test() {
    cache.get("foo", s -> loadCache(s));
}

private CompletableFuture<String> loadCache(String s) {
    cache.invalidate(s);
    return CompletableFuture.completedFuture("bar");
}
```

/cc @masonshin, who implemented Caffeine cache for `RefreshingAddressResolver`, might be interested in this issue.

### PR DESCRIPTION
**Pull request by ikhoon**
…ssResolver`

Motivation:

I saw an infinite test that never terminates on our CI build with Java 8
That is caused by a recursive update which invalidates a cache when failed to query DNS recodes.
See #3528 for details

Modifications:

- Invalidate a cache asynchronously to avoid recursive updates

Result:

- You no longer see an infinity loop or an `IllegalStateException: Recurse update`
  when invalidating a DNS cache.
- Fixes #3528

### CODE REVIEW

**Comment by ben-manes** [comment]
Alternatively, you might be able to return `null` from the loader to not cache the entry? My naive reading of the code leads me to believe that would have a similar effect, as the future's value is resolved to `null` instead.

Caffeine also offers an `AsyncCache` and custom expiration. I'd have hoped that some of this code could be simpler by using that, e.g. by not scheduling the invalidation yourself. In that instance the entry could be resolved as expired immediately to cause it to be evicted.

**Comment by ikhoon** [comment]
> Alternatively, you might be able to return null from the loader to not cache the entry? My naive reading of the code leads me to believe that would have a similar effect, as the future's value is resolved to null instead.

The returned `CompletableFuture` is usually resolved lazily except for some error cases. In that case, it should be difficult to run `null`.

> Caffeine also offers an AsyncCache and custom expiration. I'd have hoped that some of this code could be simpler by using that, e.g. by not scheduling the invalidation yourself. In that instance the entry could be resolved as expired immediately to cause it to be evicted.

Nice suggestion. `AsyncCache` and custom expiration look promising. Let us take a look how it works and is applicable.

**Review by trustin — APPROVED** [review]
Thanks, @ikhoon!

**Comment by trustin** [comment]
> Nice suggestion. AsyncCache and custom expiration look promising. Let us take a look how it works and is applicable.

This sounds better to me.

**Review by minwoox — APPROVED** [review]
Thanks, @ikhoon!
`AsyncCache` also sounds good.

**Comment by ikhoon** [comment]
> `AsyncCache` also sounds good.

Filed an issue for this. #3547

**Comment by trustin** [comment]
Thanks, @ikhoon. Let's merge this first and then migrate to `AsyncCache`. Special thanks to @ben-manes for chiming in. :bow:

**Pull request merged**
