### PR TITLE
Rename the `status` tag to `httpStatus` in `MeterIdPrefixFunction.ofDefault()`

### LINKED ISSUE #1215: Rename the 'status' tag to 'httpStatus' in 'MeterIdPrefixFunction.ofDefault()'
.. because `status` is somewhat unclear.

### PR DESCRIPTION
**Pull request by imasahiro**
Fixes #1215

### CODE REVIEW

**Comment by huydx** [comment]
I guess there're few more places that need to fixed as well to make test pass.

**Comment by trustin** [comment]
@imasahiro Gentle ping

**Comment by trustin** [comment]
@imasahiro Got an NPE:

```
com.linecorp.armeria.it.metric.DropwizardMetricsIntegrationTest > normal FAILED
    java.lang.NullPointerException
        at com.linecorp.armeria.it.metric.DropwizardMetricsIntegrationTest.lambda$normal$0(DropwizardMetricsIntegrationTest.java:98)
```

**Comment by imasahiro** [comment]
Passed test finally.

**Comment by trustin** [comment]
Thanks, @imasahiro!

**Pull request merged**
