### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by minwoox**
- Brotli4j 1.9.0 → 1.11.0
- Dropwizard 2.1.4 → 2.1.5
- Dropwizard Metrics 4.2.15 → 4.2.18
- fastutil 8.5.11 → 8.5.12
- GraphQL Kotlin 6.3.5 → 6.4.0
- java-jwt 4.2.2 → 4.3.0
- Micrometer 1.10.3 → 1.10.5
- Netty 4.1.87.Final → 4.1.90.Final
- Reactor Kotlin 1.2.1 → 1.2.2
- Sangria 3.5.0 → 3.5.3
- Spring 5.3.25 → 5.3.26
- Spring Boot2 2.7.8 → 2.7.10
- Build and examples
  - Dagger 2.44.2 → 2.45
  - Groovy 3.0.14 → 3.0.16
  - jmh-gradle-plugin 0.6.8 → 0.7.0
  - json-unit 2.36.1 → 2.37.0
  - Nexus publish 1.1.0 → 1.3.0
  - osdetector 3.21.1 → 3.21.7

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
Thanks @minwoox ! 🙇 👍 🙇

**Comment by jrhee17** [comment]
Actually it seems like java8 grpc tests are failing 😅    Might be worth taking a look

**Comment by minwoox** [comment]
> Actually it seems like java8 grpc tests are failing 😅 Might be worth taking a look

I completely missed this. 😅 Let me revert gRPC versions. 
https://github.com/protocolbuffers/protobuf/issues/11393

**Review by trustin — APPROVED** [review]
Thanks, @minwoox. LGTM once the build passes.

**Review by ikhoon — APPROVED** [review]
🙇‍♂️🙇‍♂️🙇‍♂️

**Pull request merged**
