### PR TITLE
Cache frontend packages

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

We're having frequent build failures due to connectivity issues with
registry.npmjs.org or raw.githubusercontent.com.

- node-gradle-plugin caches the downloaded nodejs/npm binary under a
  project directory, but our CI script caches only a home directory.
- `npm ci` command always checks whether its cache is up-to-date.
  The build will fail if it fails to contact registry.npmjs.org,
  even if we have cached data.
- `pngquant-bin` never caches when it downloads a pre-built `pngquant`
  binary file. If download fails, the build fails and there's no way
  to cache this at the moment.
- When a user runs `./gradlew lint` it triggers `:site:npmInstall`,
  even if the user is not interested in building the site. This increases
  the chance of build failure because it triggers the installation of
  `pngquant-bin`.

Modifications:

- Use the cache directories under a home directory instead of a project
  directory when building in a CI environment.
- Add `.npmrc` to `docs-client/` and `site/` with `prefer-offline=true`
  option, so that `npm ci` doesn't fail even if it failed to contact
  registry.npmjs.org.
- Renamed `:site:lint` and `:site:generateSources` to `:site:siteLint`
  and `:site:generateSiteSources` so that `./gradlew lint` or
  `./gradlew generateSources` doesn't trigger `:site:npmInstall`, which
  pulls `pngquant-bin` in.

Result:

- Much more reliable CI build.

### CODE REVIEW

**Comment by anuraaga** [comment]
Hmm thought it defaults to home directory for cache. How about setting environment variable to change the cache directory?

https://stackoverflow.com/a/45546082

**Review by minwoox — APPROVED** [review]
Thanks a lot. 🙇‍♂️

**Comment by trustin** [comment]
@anuraaga It seems like NPM actually stores its cache under a user home directory - `~/.npm`. The problem is:

- node-gradle-plugin stores its cache under a project directory. I worked around this problem using symlink.
- `npm ci` fails when it fails to check the NPM registry for staleness checks. I (hopefully) solved by enabling `prefer-offline` option.

**Comment by trustin** [comment]
Simplified even further:
- node-gradle-plugin's cache directories are automatically switched to user home directory when `CI` environment variable is available.
- Checked in `.npmrc` into each module directory so `prefer-offline` option is automatically picked up.

**Review by anuraaga — APPROVED** [review]
Nice!

**Comment by trustin** [comment]
The most frequent failure related with a frontend dependency is `pngquant-bin`, which uses [`download`](https://github.com/kevva/download) to download the prebuilt `pngquant` binary at installation time. `download` currently doesn't support any caching. If it fails to download the prebuilt binary, it falls back to building from source code, which is not possible because our Docker image doesn't have `libpng-dev` installed.

To solve this problem, we have to: stop using `pngquant-bin`, install `libpng-dev` or ask the maintainers to implement caching.

**Comment by trustin** [comment]
What's interesting is that `pngquant-bin` is only required when building `:site`. It seems like we're triggering `:site:npmInstall` even when unnecessary. Let me fix this as well.

**Comment by trustin** [comment]
> What's interesting is that `pngquant-bin` is only required when building `:site`. It seems like we're triggering `:site:npmInstall` even when unnecessary. Let me fix this as well.

Fixed in e400e2d20bb32acc47d9d9e6335ca359605846ff

**Comment by trustin** [comment]
Note that `:site:site` can still fail when it fails to download the pre-built `pngquant` binary but other build profiles will not fail anymore.

**Review by ikhoon — APPROVED** [review]
Thanks a lot! @trustin 🙇‍♂️

**Pull request merged**
