### PR TITLE
Easier ClientOptions construction and correct client derivation

### PR DESCRIPTION
**Pull request by trustin**
Motivation:
- The construction of ClientOptions is not very convenient when
  specifying decorators and HTTP headers because a ClientOption does not
  provide an easy way to add a decorator or an HTTP header to an
  existing ClientOptions.
- When creating a derived client, a user can override various
  ClientOptions, but some options such as DECORATION can never be
  overridden.

Modifications:
- Change how ClientBuilder handles decorators and HTTP headers
  - Specifying a decoration will not replace the previous decoration
    anymore. The previous decoration and the new decoration will be
    merged automatically.
  - Specifying an HttpHeaders will not replace the previous headers
    anymore. The previous headers and the new headers will be merged
    automatically.
- Add ClientOptionsBuilder
- Add AbstractClientOptionsBuilder to share the common operations
  between ClientBuilder and ClientOptionsBuilder
- Replace ClientOptionDerivable with ClientBuilderParams so that enough
  information is preserved to create a derived client.
  - This removes withOptions() methods.
- Add Clients.newDerivedClient(client, configurator)
  - A user can override the options of the client being derived a lot
    more flexibly.
- Miscellaneous:
  - Add missing Javadoc comment for DefaultHttpData

Result:
- ClientBuilder and ClientOptionsBuilder let a user build client options
  much more easily.
- A user can create a derived client with more freedom.
- The behavior of Clients.newDerivedClient() is changed in a backward
  incompatible way when additional options contain DECORATIONS or
  HTTP_HEADERS due to how ClientOptionsBuilder merges them.
- A user cannot create a derived client using withOptions() because it's
  gone due to its design flaw.

### CODE REVIEW

**Comment by inch772** [comment]
LGTM!

**Comment by trustin** [comment]
@inch772 Will you please merge, then? :-)

**Comment by inch772** [comment]
Oh~ sorry I missed pressing the merge button ;-)

**Comment by trustin** [comment]
Thanks, @inch772 !

**Pull request merged**
