### PR TITLE
Fix flaky test in Consul

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

```
ConsulEndpointGroupTest > initializationError FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in
    com.linecorp.armeria.internal.consul.ConsulTestBase that uses com.pszymczyk.consul.ConsulStarterBuilder null within 10 seconds.
```

Modifications:

- Increase the timeout in `await()` to reduce flakiness

Result:

- Clean up flaky test in Consul

### CODE REVIEW

**Comment by ikhoon** [comment]
Do not review this PR yet.
I opened this PR to run Consul tests in the CI evironment.

**Comment by ikhoon** [comment]
The flaky test on Consul seems to be reduced. PTAL. 🙇‍♂️

**Review by minwoox — APPROVED** [review]
👍

**Review by trustin — APPROVED** [review]
Thanks, @ikhoon !

**Pull request merged**
