### PR TITLE
Fix query and path not encoded as expected.

### PR DESCRIPTION
**Pull request by kojilin**
Apply this change will use okhttp3.HttpUrl's getEncodedQuery and getEncodedPath api to build the armeria's url path & query. These API will follow @Path and @Query's encoded param.

### CODE REVIEW

**Comment by kojilin** [comment]
And this will change behavior, if user using `@Path` or `@Query` before with or without `encoded = true`. Please check behavior before upgrade to new version.

**Comment by kojilin** [comment]
add more test to check `@Field` annotation is followed.

**Comment by trustin** [comment]
Thanks all. Will merge once CI passes.

**Comment by trustin** [comment]
Thanks, @kojilin !

**Pull request merged**
