### PR TITLE
Fix a bug where `HttpResponse` can't complete with `CompletionStage`

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

`CompletionStage<T> CompletableFuture.minimalCompletionStage()` returns a `MinimalStage` which implements `CompletionFuture` and raises `UnsupportedOperationException` if the methods only in `CompletionFuture` are called.

`HttpResponse.of(CompletionStage<HttpResponse>)` checks if the given value is an instance of `CompletableFuture` to use an optimized path for `CompletableFuture`. It is not working because `MinimalStage` can be set to the method parameter easily.
```java
CompletableFuture<HttpResponse> future = new CompletableFuture<>();
HttpResponse.of(future.minimalCompletionStage());
```

Discord discussion: https://discord.com/channels/1087271586832318494/1087272728177942629/1153277808630566942

Modifications:

- Do not check if a `CompletationStage` is an instance of `CompletableFuture` in `HttpResponse` and `StreamMessage`.

Result:

You no longer see `UnsupportedOperationException` when creating an `HttpResposne` with `CompletationStage`.

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
TIL 😄    Thanks for the report and fix @tobias- @ikhoon    🙇 👍 🙇 

(Please also check lint/test failures)

**Comment by tobias-** [comment]
Considering this bug, there seems to be one more piece of code that's basically the same. Could this have a path that could cause the same problem?

I'm thinking of `DefaultStreamMessage.cleanupObjects()` where `completeExceptionally` is called (it's another one of the overridden method in `MinimalStage`).

**Comment by ikhoon** [comment]
> Could this have a path that could cause the same problem?

Possible. I tried to check all usages of `CompletionStage` when creating this PR but let me double-check.

> I'm thinking of DefaultStreamMessage.cleanupObjects() where completeExceptionally is called

Good point. I guess we can ignore it because the `CompletableFuture` is created internally which is an instance of `AwaitDemandFuture`. Let me change the type to `AwaitDemandFuture` for clarity.

**Review by minwoox — APPROVED** [review]
Thanks!

**Comment by minwoox** [comment]
@ikhoon 👍 👍 👍 
@tobias- Thanks for the report and through review! 😄

**Pull request merged**
