### PR TITLE
Update the dependencies

### PR DESCRIPTION
**Pull request by trustin**
- Awaitility 2.0.0 -> 3.0.0
- Brave 4.0.6 -> 4.2.0
- fastutil 7.1.0 -> 7.2.0
- GRPC 1.2.0 -> 1.3.0
- Jackson 2.8.7 -> 2.8.8
- Jetty 9.4.3 -> 9.4.4
- JSON-unit 1.21.0 -> 1.22.0
- Kafka 0.10.2.0 -> 0.10.2.1
- Mockito 2.7.21 -> 2.7.22
- Netty 4.1.9 -> 4.1.10
- Tomcat 8.5.13 -> 8.5.14
- ZooKeeper 3.4.9 -> 3.4.10
- Build plugins
  - ProGuard 5.3.2 -> 5.3.3
  - Protobuf 0.8.0 -> 0.8.1
- Miscellaneous:
  - Fix typo in messages.proto (come.linecorp -> com.linecorp)
  - Fix a bug in core/build.gradle where not all dependencies are passed
    to ProGuardTask (fixed by @anuraaga)

### CODE REVIEW

**Comment by trustin** [comment]
@anuraaga Please check I didn't break anything while upgrading to GRPC 1.3.0 :-)

**Comment by anuraaga** [comment]
Thanks for fixing the proto package!

I'm not sure what this build failure is - :core:trimShadedJar is failing with an error dealing with grpc-testing protos. Two things strange about that is :core doesn't depend on grpc, and non-testing jar doesn't depend on grpc-testing. Do you know what could be going on?

**Comment by trustin** [comment]
@anuraaga Will investigate

**Comment by anuraaga** [comment]
Ah I see - it's because we depend on other projects to allow automatically determining what classes are used in the core jar during trimming.

I checked out this branch and was able to get it to work by making sure to add the other projects' dependencies as libraryjars. Go ahead and take this commit :)

https://github.com/line/armeria/commit/d27dbbcd1f805401fc12b8f49b7a8fea93e36f19

**Comment by trustin** [comment]
@anuraaga Thanks! Updated the PR.

**Pull request merged**
