### PR TITLE
Improve the usability of HttpResponseException

### PR DESCRIPTION
**Pull request by hyangtack**
Modifications:

- Remove ‘abstract’ keyword.
- Add a constructor which creates a new instance with HTTP status code.

### CODE REVIEW

**Comment by hyangtack** [comment]
@imasahiro If you have any special reason to make it as abstract class, please let us know! :-)

**Comment by minwoox** [comment]
We might remove the synchronized keyword on fillInStackTrace method as well.. right?

**Comment by hyangtack** [comment]
@minwoox Removed! 😄

**Comment by trustin** [comment]
Please feel free to merge once @imasahiro approves.

**Comment by imasahiro** [comment]
LGTM (I forgot actual reason why I put `abstract` to this class...)

**Comment by imasahiro** [comment]
Hm, travis failed to download JDK.. I don't think it is related to this PR but need to update our script?

```
--2017-07-28 01:50:01--  http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz?AuthParam=1501206720_ec3bb7ff704bb29199ad87982511eca3

Connecting to download.oracle.com (download.oracle.com)|65.158.47.50|:80... connected.

HTTP request sent, awaiting response... 404 Not Found

2017-07-28 01:50:02 ERROR 404: Not Found.
```

**Comment by hyangtack** [comment]
@imasahiro I see. I will change the url. :-)

**Comment by hyangtack** [comment]
Reverted the fix about JDK download URL because #704 fixes it.

**Pull request merged**
