### PR TITLE
Cancel duplicated GitHub Action workflows

### LINKED ISSUE #3621: Cancel duplicated GitHub Action workflows
It's quite normal the author of a pull request will push multiple commits in a short time, for example, me 🤣 , and the workflows for previous commits make no sense exception for the latest commit, like below, let's cancel the old workflows when new commits are pushed

Screen Shot 2021-06-07 at 16 19 13

### PR DESCRIPTION
**Pull request by kezhenxu94**
Closes #3621

### CODE REVIEW

**Comment by kezhenxu94** [comment]
For self-hosted runners, I think this is a save of resources, and time

**Comment by ikhoon** [comment]
I tried `cuncurrency.cancel-in-progres` a few weeks ago, and unfortunately, it didn't work as expected. The feature is in beta and is not stabilized. 
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
Anyway, let's try them again. We don't know whether it works before it is applied.

**Review by ikhoon — APPROVED** [review]

**Comment by kezhenxu94** [comment]
> I tried `cuncurrency.cancel-in-progres` a few weeks ago, and unfortunately, it didn't work as expected. The feature is in beta and is not stabilized.
> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
> Anyway, let's try it again. We don't know whether it works before it is applied.

We've been using this in Apache SkyWalking and Apache Airflow, and it turns out to work well. Example https://github.com/apache/skywalking/actions/runs/908157341

> Canceling since a higher priority waiting request for 'e2e-features-7070' exists

Screen Shot 2021-06-07 at 20 48 25

**Review by minwoox — APPROVED** [review]
Thanks a lot. 😄

**Comment by ikhoon** [comment]
Let me merge this PR and check that the cancellation is working for self-hosted runners.

**Comment by ikhoon** [comment]
It worked well! https://github.com/line/armeria/actions/runs/920359021
Thanks again. @kezhenxu94

**Comment by kezhenxu94** [comment]
> It worked well! https://github.com/line/armeria/actions/runs/920359021
> Thanks again. @kezhenxu94

Glad it helps!!!

**Comment by ikhoon** [comment]
@trustin's Github Actions trigger script also works nicely. 😆 https://gist.github.com/trustin/05cbb70e22fc5e7c8b5ffbd1f0d99c8b#file-git-trigger-build-sh

**Pull request merged**
