### PR TITLE
Fix #186 DocService Struct field docstrings are not reliably included

### LINKED ISSUE #186: DocService - Struct field docstrings are not reliably included
When applying the docstring changes to an actual service, I found that field comments don't always show up, even though they are included in the JSON. I suspect something to do with the "field key" computation.

### PR DESCRIPTION
**Pull request by jongyeol**
# Changes

### Before:
* functions: Supports A style only.
* structs: Supports A style only.

### Fixed:
* functions: Supports A style only.
* structs: **Supports both A and B styles**.

# Reference

### A style
```
/**
    A TokenRange describes part of the Cassandra ring, it is a mapping from a range to
    endpoints responsible for that range.
    @param start_token The first token in the range
    @param end_token The last token in the range
    @param endpoints The endpoints responsible for the range (listed by their configured listen_address)
    @param rpc_endpoints The endpoints responsible for the range (listed by their configured rpc_address)
*/
struct TokenRange {
    1: required string start_token,
    2: required string end_token,
    3: required list<string> endpoints,
    4: optional list<string> rpc_endpoints
    5: optional list<EndpointDetails> endpoint_details,
}
```

### B style
```
/**
    Methods for fetching rows/records from Cassandra will return either a single instance of ColumnOrSuperColumn or a list
    of ColumnOrSuperColumns (get_slice()). If you're looking up a SuperColumn (or list of SuperColumns) then the resulting
    instances of ColumnOrSuperColumn will have the requested SuperColumn in the attribute super_column. For queries resulting
    in Columns, those values will be in the attribute column. This change was made between 0.3 and 0.4 to standardize on
    single query methods that may return either a SuperColumn or Column.

    If the query was on a counter column family, you will either get a counter_column (instead of a column) or a
    counter_super_column (instead of a super_column)
 */
struct ColumnOrSuperColumn {
    /**
     * The Column returned by get() or get_slice().
     **/
    1: optional Column column,
    /**
     * The SuperColumn returned by get() or get_slice().
     **/
    2: optional SuperColumn super_column,
    /**
     * The Counterolumn returned by get() or get_slice().
     **/
    3: optional CounterColumn counter_column,
    /**
     * The CounterSuperColumn returned by get() or get_slice().
     **/
    4: optional CounterSuperColumn counter_super_column
}
```

### CODE REVIEW

**Comment by jongyeol** [comment]
@anuraaga , @trustin , Sorry for late. I fixed #186 . Review please. :)

**Comment by trustin** [comment]
@jongyeol LGTM, but it seems like you need to fix the tests as well.

**Comment by trustin** [comment]
https://travis-ci.org/line/armeria/builds/138080971#L1181

**Comment by jongyeol** [comment]
@trustin, Sure, I'll fix it.

**Pull request merged**
