### PR TITLE
Add Gradle(Kotlin) tab to RequiredDependencies component

### LINKED ISSUE #4106: build.gradle.kts compatible documentation
https://armeria.dev/docs/client-retrofit/

Currently, armeria docs was written in this form.

```
dependencies {
    implementation platform('com.linecorp.armeria:armeria-bom:1.14.1')

    ...
    implementation 'com.linecorp.armeria:armeria-retrofit2'
}
```

It's a valid build.gradle groovy script.

But if the document is written in this form:

```
dependencies {
    implementation(platform("com.linecorp.armeria:armeria-bom:1.14.1"))

    ...
    implementation("com.linecorp.armeria:armeria-retrofit2")
}
```

It's also compatible with build.gradle.kts(kotlin) script.
Recently, a lot of users are starting to use kotlin scripting.

I suggest to use this form(or display "Gradle", "Gradle(Kotlin)", "Maven" tabs at here)
image

### PR DESCRIPTION
**Pull request by clatisus**
Motivation:

More users are starting to use Kotlin scripting, add this tab can help them copy-paste codes

Modifications:

- Add Gradle(Kotlin) tab to RequiredDependencies component

Result:

- Closes #4106 
- Test result:

| | Screenshot|
|---|---|
| Gradle |image |
| Kotlin| image|
| Gradle| image|
| Kotlin| image|
| Gradle| image|
| Kotlin| image|

### CODE REVIEW

**Comment by ikhoon** [comment]
Overall, looking good! Would you mind updating `setup.mdx` file together?

**Comment by clatisus** [comment]
> Overall, looking good! Would you mind updating `setup.mdx` file together?

@ikhoon comment addressed, PTAL again

**Review by trustin — APPROVED** [review]
This is awesome, @clatisus! Thanks a lot for this change. 🙇:+1:

**Review by ikhoon — APPROVED** [review]
Thanks, @clatisus!

**Pull request merged**
