### PR TITLE
Fixed a bug where logs produced by `Flags` were not appended to `RequestContextExportingAppender`

### LINKED ISSUE #5327: `RequestContextExportingAppender` has a dependency on `Flags` which partially breaks logging
When Armeria is configured with Logback and `RequestContextExportingAppender` with custom headers, and when multiple Netty versions are present in the classpath, logs for `Flags` will be missing.

When the following appender with a custom header is configured in Logback:
```xml
<appender name="ARMERIA_KAFKA" class="com.linecorp.armeria.common.logback.RequestContextExportingAppender">
  <appender-ref ref="KAFKA" />
  <export>req.headers.x-real-ip</export>
</appender>
```

The Logback setup flow will behave as follows:
1. [`setExport()`](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/logback/logback12/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java#L148) is called for `req.headers.x-real-ip`
2. Eventually, we call [`ExportGroupBuilder.requestHeader()`](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/core/src/main/java/com/linecorp/armeria/common/logging/ExportGroupBuilder.java#L127-L132)
3. Following `toHeaderName()`, we reach [this call to `Flags.validateHeaders()`](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java#L991-L993)
4. This initializes the `Flags` class, which initializes `TransportType`, which initializes `TransportTypeProvider`
5. `Flags` will log the values of all flags, and `TransportTypeProvider` will [validate Netty versions](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java#L60-L94) and log a warning in case of inconsistencies

However, since we're still setting up Logback, no appenders are configured on `ROOT` level, so this information will never be logged.

By removing `<export>req.headers.x-real-ip</export>` or using `req.headers.user-agent` (a known and pre-cached header), the call to `Flags.validateHeaders()` never happens, and the `Flags` class is initialized after Logback setup is done. In that case, the logs will appear as expected.

We can probably fix this by breaking the dependency between `RequestContextExportingAppender` and `Flags.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

If `Flags` class is initialized before `RequestContextExportingAppender` is registered to the root logger,
the logs produced `Flags` in the initialization of the class are silently ignored.
See #5327 for the details.

Modifications:

- Lazily create `RequestContextExporterBuilder` to not initialize `Flags` while ` RequestContextExportingAppender` is being initialized.
  - `RequestContextExporterBuilder` is created when `FlagsLoaded.get()` is true.

Result:

- `Flags` now correctly logs all messages when `RequestContextExportingAppender` is configured.
- Fixes #5327

### CODE REVIEW

**Comment by ikhoon** [comment]
Tried to create a test but it wasn't easy because the problem only occurred with `main` method.

**Review by KarboniteKream — APPROVED** [review]
I've confirmed this fixes the issue on our affected servers. ❤️

**Comment by ikhoon** [comment]
Thank you for your quick confirmation. ❤️

**Review by jrhee17 — APPROVED** [review]
Changes make sense 👍   Thanks @ikhoon 🙇 👍 🙇

**Review by minwoox — APPROVED** [review]
Thanks! 👍 👍 👍

**Pull request merged**
