### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by trustin**
- Dropwizard Metrics 4.1.11 -> 4.1.12.1
- gRPC 1.31.0 -> 1.31.1
- kafka-clients 2.5.0 -> 2.6.0
- Micrometer 1.5.3 -> 1.5.4, 1.3.11 -> 1.3.12
- RxJava 3.0.5 -> 3.0.6
- Spring Boot 2.3.2 -> 2.3.3
- Shaded dependencies:
  - fastutil 8.4.0 -> 8.4.1
  - JCTools 3.0.0 -> 3.1.0
- Examples:
  - scalapb-runtime 0.10.7 -> 0.10.8
- Build:
  - Gradle 6.5.1 -> 6.6
  - finagle-serversets 20.7.0 -> 20.8.0
  - gax-grpc 1.57.1 -> 1.58.2
  - JMH 1.23 -> 1.25
  - Mockito 3.4.6 -> 3.5.2
  - monix-reactive 3.2.2 -> 3.2.2+43
  - protobuf-gradle-plugin 0.8.12 -> 0.8.13
- Also updated frontend dependencies

### CODE REVIEW

**Comment by trustin** [comment]
@okue @gary-lo Do you think we should update to Kotlin 1.4.0 in this release?

**Comment by ikhoon** [comment]
There is an incompatibility issue on akka-grpc.
```
om.linecorp.armeria.server.grpc.GrpcWebServiceTest > initializationError FAILED
    java.lang.IllegalStateException: You are using version 10.2.0 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.0 of the [akka-http2-support] artifacts to your project. See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
        at akka.util.ManifestInfo.checkSameVersion(ManifestInfo.scala:217)
        at akka.util.ManifestInfo.checkSameVersion(ManifestInfo.scala:195)
        at akka.http.scaladsl.HttpExt.<init>(Http.scala:79)
        at akka.http.scaladsl.Http$.createExtension(Http.scala:1080)
        at akka.http.scaladsl.Http$.createExtension(Http.scala:814)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1145)
        at akka.actor.ExtensionId.apply(Extension.scala:78)
        at akka.actor.ExtensionId.apply$(Extension.scala:77)
        at akka.http.scaladsl.Http$.apply(Http.scala:1075)
        at akka.http.javadsl.Http.delegate$lzycompute(Http.scala:47)
        at akka.http.javadsl.Http.delegate(Http.scala:47)
        at akka.http.javadsl.Http.defaultServerHttpContext(Http.scala:762)
        at akka.http.javadsl.Http.bindAndHandleAsync(Http.scala:300)
        at com.linecorp.armeria.server.grpc.GrpcWebServiceTest.setUp(GrpcWebServiceTest.java:73)
```

**Comment by minwoox** [comment]
> There is an incompatibility issue on akka-grpc.

Let me handle this. 😉

**Comment by okue** [comment]
I think not so many users are using Kotlin 1.4 now because Ktlint for Kotlin 1.4.0 is not released.
https://github.com/pinterest/ktlint/releases

**Pull request merged**
