### PR TITLE
Downgrade gRPC and protobuf dependencies

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

https://github.com/protocolbuffers/protobuf/issues/11393

```
        Caused by:
        java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
            at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeStringNoTag(CodedOutputStream.java:2153)
            at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeString(CodedOutputStream.java:1922)
            at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:3195)
```

Modifications:

- Downgrade protobuf and gRPC

Result:

- Users no longer encounter an exception when using protobuf, grpc with jre 8

### CODE REVIEW

**Comment by jrhee17** [comment]
Although I think this PR is ready, I would like to run the CI one more time after #4661 is merged 🙇

**Review by ikhoon — APPROVED** [review]
👍

**Comment by ikhoon** [comment]
Re-ran the failed Java 8 test.

**Comment by jrhee17** [comment]
It seems like gax-grpc was unintentionally resolving protobuf to a more recent version.
We may consider more stricter dependency resolution failure strategies (if there is an ability to limit to certain artifacts)

**Review by minwoox — APPROVED** [review]
Thanks!

**Pull request merged**
