### PR TITLE
Fix flaky `HeadMethodLeakTest`

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

A pooled `ByteBuf` instance is reused so we can't tell its `refCnt` is 0 forever after the `ByteBuf` is freed.
https://github.com/netty/netty/blob/44b7e5b12d8dff3d07dfb773680120cc20f7e203/buffer/src/main/java/io/netty/buffer/PooledDirectByteBuf.java#L38
When I logged `refCount` of `ByteBuf`s in `HeadMethodLeakTest`, they became 1 from 0 during assertions.

Modifications:

- Use Unpooled allocator instead

Result:

Clean up flaky tests

### CODE REVIEW

**Review by trustin — APPROVED** [review]
Thanks, @ikhoon 🙇

**Review by minwoox — APPROVED** [review]
Thanks! 👍 👍 👍

**Review by jrhee17 — APPROVED** [review]
While the current fix looks good 👍   It seems like there is another leak from the CI.. taking a look

**Comment by ikhoon** [comment]
>  It seems like there is another leak from the CI.

It might be a known issue. #4141
Let me merge this PR to make our CI stable.

**Pull request merged**
