### PR TITLE
Improve JMH integration

### PR DESCRIPTION
**Pull request by trustin**
- Apply JMH plugin for all Java projects
- Add JMH annotation processor to the dependencies so that a developer
  can launch a benchmark from his or her IDE
- Add 'jmh.*' properties for tuning JMH plugin configuration
  - Rename grpcJmh.upstream to jmh.grpcUpstream

### CODE REVIEW

**Comment by trustin** [comment]
On the other hand, I was able to use https://github.com/trustin/perf-map-agent/ to resolve the symbols of Java application. However, I had to remove it from this PR since it's GPL'd.

After then, I realized I don't need `perf-map-agent` but just install the HSDIS plugin for OpenJDK: https://github.com/abak/openjdk-hsdis

**Comment by trustin** [comment]
Ended up making some additional modifications to get it work on my Linux: https://github.com/trustin/openjdk-hsdis

**Comment by trustin** [comment]
It seems like the annotation processor and the gradle plugin do not get along. Will investigate a little bit more..

**Comment by trustin** [comment]
Removed the annotation processor because it causes double-generation of benchmark classes (one from IDE and the other from the plugin), making things go unexpectedly.

**Comment by trustin** [comment]
Build failure unrelated with this PR. Filed a separate issue: #809

**Comment by anuraaga** [comment]
FYI I have found that since Gradle 4.2, startup is blazingly fast, so I have set IntelliJ to Delegate builds to Gradle, which usually handles annotation processors smoothly.

Otherwise for Gradle / IntelliJ interop I was using these hacks but have their own problems, as does gradle-apt-plugin's approach too...

https://github.com/curioswitch/curiostack/blob/master/tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java#L374

https://github.com/curioswitch/curiostack/blob/master/tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java#L445

**Pull request merged**
