### PR TITLE
Replace react-dropdown with Material-UI's Select

### PR DESCRIPTION
**Pull request by KarboniteKream**
### Motivation
- In effort to reduce the JS bundle size, we can use Material-UI components instead of extra dependencies

### Modifications
- Replace `react-select` with Material-UI's `Select` component
- Use `value=""` to keep controlled component "uninitialized" so the user can repeat the last selection
  - Before this change, the user had to select another option, which is impossible if there's only one item

2020-11-03_17 21 42_%pn_8eowwpdkNW

### Result
- Unify DocService appearance and slightly improve UX
- Remove a dependency and reduce `docs-client` bundle size by 10 kB

### CODE REVIEW

**Comment by KarboniteKream** [comment]
I'm planning to do the same for `react-select` (used by `GoToSelect`), but since the change is much bigger (but makes the code much simpler), I'll be making a separate PR.

**Review by trustin — APPROVED** [review]
Nice! I wonder if we can migrate to a more modern and desktop friendly widgets completely in the future, e.g. Chakra, Antd... 😅

**Comment by KarboniteKream** [comment]
I think it shouldn't be too problematic, the `docs-client` is fairly simple (apart from the current `GoToSelect` 😅).
I'm not familiar with Chakra or Ant, let me take a look! 🙂

**Review by minwoox — APPROVED** [review]
Thank you so much for cleaning up the dependency. 😄

**Review by ikhoon — APPROVED** [review]
Niceee!

**Pull request merged**
