### PR TITLE
Work around the test failures in ThriftOverHttpClientTServletIntegrationTest

### PR DESCRIPTION
**Pull request by trustin**
- Retry the test up to 10 times until it does not get
  ClosedSessionException.
- Add FIXMEs so that we can fix this better later

Not an ideal fix but I think it's better than just ignoring it completely.

### CODE REVIEW

**Comment by trustin** [comment]
Builds:
- https://ci.appveyor.com/project/trustin/armeria/build/master.244
- https://ci.appveyor.com/project/trustin/armeria/build/master.245

**Comment by trustin** [comment]
@anuraaga Travis CI failure:

```
:shaded-test:shadedGrpcTest[jetty-alpn-agent] Using: alpn-boot-8.1.10.v20161026.jar
com.linecorp.armeria.client.grpc.GrpcClientTest > cancelAfterFirstResponse FAILED
    java.lang.AssertionError: 
    Expected size:<1> but was:<0> in:
    <[payload {
      body: "\000\000\000\000\000\000\000\000\000..."
    }
    ]>
        at com.linecorp.armeria.client.grpc.GrpcClientTest.cancelAfterFirstResponse(GrpcClientTest.java:376)
```

**Comment by anuraaga** [comment]
@trustin I've had what I think fixes it in the debug form PR, should I extract it to a separate one?

**Comment by trustin** [comment]
@anuraaga Ah, no worries then. See you there. :-)

**Comment by trustin** [comment]
All builds have passed. Will merge.

**Pull request merged**
