### PR TITLE
Add more community articles

### PR DESCRIPTION
**Pull request by trustin**
- Added the articles from the following contributors:
  - @dogacel
  - @dgahn
  - @tomatophobia

### CODE REVIEW

**Comment by trustin** [comment]
Please feel free to:

- leave the comments on the article description if you think the description could be improved.
- suggest other community articles, slides and videos I forgot to add yet.

**Review by Dogacel — APPROVED** [review]
Looks pretty good on my end, thank you 🙇

**Review by jrhee17 — APPROVED** [review]
Thanks @dgahn @Dogacel @trustin !

**Review by minwoox — APPROVED** [review]
LGTM once `TBW` is done. 👍

**Comment by trustin** [comment]
It's now ready for the review. I also added the posts from @tomatophobia.

**Review by ikhoon — APPROVED** [review]
Thanks! 🙇‍♂️🙇‍♂️

**Pull request merged**
