### PR TITLE
Update documentation for default value in Backoff.exponential where multiplier is not specified

### PR DESCRIPTION
**Pull request by roderick675**
Motivation:

Docs were confusing when using the framework. Needed to dig into the code to find the default multipler. So let's add it in the documentation

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
👍 👍

**Comment by ikhoon** [comment]
@roderick675 Would you fix the checkstyle violation?

**Comment by roderick675** [comment]
@ikhoon done!

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by ikhoon — APPROVED** [review]
Thanks!

**Pull request merged**
