### PR TITLE
Remove deprecated API usages

### PR DESCRIPTION
**Pull request by minwoox**

### CODE REVIEW

**Comment by minwoox** [comment]
I couldn't remove all the usages because it took more time than I thought. Let me continue to working on this later when I have some time. 😉

**Review by ikhoon — APPROVED** [review]
🙇‍♂️🙇‍♂️

**Review by jrhee17 — APPROVED** [review]
What was the motivation for this? Did you just go through IDE warning logs?
Anyways, thanks for the cleanup @minwoox 🙇 👍 🙇

**Comment by minwoox** [comment]
I've used `-Xlint:deprecation`.
https://discuss.gradle.org/t/what-is-xlint-deprecation-and-how-to-use-it/40270/5
While I was creating the PR that updates dependencies, I found that it was challenging to make changes after APIs are gone. 😉

**Pull request merged**
