### PR TITLE
Add virtual office hours to the web site

### PR DESCRIPTION
**Pull request by trustin**
- Added a link to the virtual office hours page in the community home.
- Added the virtual office hours page.
- Added the office hours banner image to `src/design` for future use.
- Miscellaneous:
  - Updated Node.js and NPM.
  - Downgraded `package-lock.json` version from 2 (for npm 7) to 1 (for
    npm 6).

### CODE REVIEW

**Comment by trustin** [comment]
Preview:
preview

**Review by ikhoon — APPROVED** [review]
Awesome page! Thanks @trustin 🙇‍♂️

**Review by minwoox — APPROVED** [review]
Thanks! ❤️

**Comment by trustin** [comment]
Thanks for reviewing. :bow:

**Pull request merged**
