### PR TITLE
typographical error changed

### PR DESCRIPTION
**Pull request by brant-hwang**
HttpConfigurator.java ExtenedHttpToHttp2ConnectionHandler => ExtendedHttpToHttp2ConnectionHandler

### CODE REVIEW

**Comment by trustin** [comment]
Let me first add the coding style guide so your IDE does not change the imports unnecessarily. Meanwhile, could you update the PR so it does not change the unrelated lines?

**Comment by brant-hwang** [comment]
Oh. Thank you for you comments. I will change the IntelliJ auto import option the first and then send it again.

**Comment by trustin** [comment]
Could you please squash the commits and update the commit message? 

```
Fix a typo in ExtendedHttpToHttp2ConnectionHandler

ExtenedHttpToHttp2ConnectionHandler -> ExtendedHttpToHttp2ConnectionHandler
```

**Comment by brant-hwang** [comment]
updated commit message!

**Comment by trustin** [comment]
Thanks, but I ended up merging #9 instead, which includes the same fix and more. Please don't get discouraged - let me look forward your upcoming contributions :-)

**Pull request closed without merging**
