### PR TITLE
Force-reinitialize `io.netty.channel.unix.Socket` after loading a native library

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

Since 4edffc8c11bd74665d652a1fd108d6a0307b6733, we check whether epoll
and io_uring native transports are available or not upfront. However,
there's a known issue in Netty where `Socket.isIPv6Preferred()` can
return a wrong value when more than one native transport are loaded:

- https://github.com/netty/netty/issues/10909

Modifications:

- Force-reinitialize `Socket` by calling its private method after a new
  native library is loaded, so that `Socket.isIPv6Preferred()` always
  returns a correct value.

Result:

- We don't get the 'Address family not supported by protocol' or
  'Connection refused' error anymore.
- Works around https://github.com/netty/netty/issues/10909 until it's
  fixed.

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks! @trustin

**Review by minwoox — APPROVED** [review]
Thanks a lot!

**Comment by trustin** [comment]
We don't need to merge this PR if we ship a newer Netty version. Let's close it rather than merging it if we update Netty in the next release.

**Comment by trustin** [comment]
Fixed by upgrading Netty to a newer version.

**Pull request closed without merging**
