### PR TITLE
Remove Spring Boot 1 integration modules

### LINKED ISSUE #4651: Stop support for Spring Boot 1
We have tried to maintain Spring Boot 1 integration modules for a long time even after Spring ceased maintenance. https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019

Spring Boot 3 has been released and we are going to support it soon. #4574 Spring Boot has made lots of breaking changes in their public API which compelled us to use reflections as workarounds which make us difficult to maintain all versions.

I don't see users, who don't upgrade their Spring Boot version to 2 or 3, upgrade Armeria version to the latest one. We may make an announcement for deprecation in 1.22.0 and remove the modules in the following version.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Spring Boot 3 has been released and we added new modules for Spring Boot 3 #4574. Spring also stopped support for Spring Boot 1 a long time ago. https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019 See #4651 for the details

Modifications:

- Remove `boot1-autoconfigure` and `boot1-starter` modules

Result:

- You no longer use Spring 1 integration with the latest Armeria version.
- Closes #4651

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
👋 👋 👋

**Review by jrhee17 — APPROVED** [review]
Thanks @ikhoon ! 👋 👋 👋

**Comment by ikhoon** [comment]
Updated Spring Boot 3 version to [3.0.5](https://github.com/spring-projects/spring-boot/releases/tag/v3.0.5)

**Review by trustin — APPROVED** [review]
🧙🔥🍀💨

**Pull request merged**
