### PR TITLE
Release notes for 1.31.1

### PR DESCRIPTION
**Pull request by jrhee17**
Screenshot 2024-11-21 at 14-47-09 1 31 1 release notes — Armeria release notes

### CODE REVIEW

**Comment by ikhoon** [comment]
Optional) It is unrelated to this PR but should we exclude `protobuf-java` dependency from `protobuf-jackson` using `exclusions` in `dependencies.toml`? As the result is the same, it is okay to handle it later.

**Review by ikhoon — APPROVED** [review]
🙏

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Comment by jrhee17** [comment]
> should we exclude protobuf-java dependency from protobuf-jackson using exclusions in dependencies.toml

Probably makes more sense in case other modules also try to expose `protobuf-jackson` in the future. Done

**Pull request merged**
