### PR TITLE
Re-indent gRPC example

### PR DESCRIPTION
**Pull request by icepeppermint**
Motivation:

This is my first contribution!
This PR contains only re-indent :)

Modifications:

- Re-indent some codes

Result:

- The behavior of the code is not affected

### CODE REVIEW

**Comment by ikhoon** [comment]
Could you sign our CLA?

**Comment by icepeppermint** [comment]
> Could you sign our CLA?

Oh, thank you for your comment :)
I just signed the CLA.

**Review by minwoox — APPROVED** [review]
Thanks! 😉

**Review by trustin — APPROVED** [review]
Thanks a lot for your first contribution. Looking forward to more in the future :wink:

**Review by ikhoon — APPROVED** [review]
Thanks! @icepeppermint

**Pull request merged**
