### PR TITLE
Fix a typo of link in the REST tutorials

### PR DESCRIPTION
**Pull request by jongmin92**
Motivation:
스크린샷 2021-08-24 오후 7 34 24
스크린샷 2021-08-24 오후 7 34 28

Modifications:

- Fix `implenment` typo to `implement`.

Result:

- Fix the REST tutorial documents link.

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Nice catch!

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Comment by minwoox** [comment]
Thanks a lot, @jongmin92!

**Comment by trustin** [comment]
Oops! Thanks for fixing this, @jongmin92 :bow:

**Pull request merged**
