### PR TITLE
Update micrometer to 1.0.0-rc.6

### PR DESCRIPTION
**Pull request by imasahiro**

### CODE REVIEW

**Comment by trustin** [comment]
@imasahiro I didn't know the pause detector changes were included in rc6. What's the default pause detector now?

**Comment by imasahiro** [comment]
@trustin  [Here](https://github.com/micrometer-metrics/micrometer/commit/eb53f71e405f09c0ce4f88d98689b1986b8b96a8) is actual commit to make pause detector configurable included in rc6.  `SimplePauseDetector` is still used by default but we can override this using MeterRegistryConfigurer.

```java
@Bean
public MeterRegistryConfigurer configurer() {
    return r -> r.config().pauseDetector(new NoPauseDetector());
}
```

**Comment by trustin** [comment]
I see. How about defaulting to `NoPauseDetector` in `PrometheusMeterRegistries`, `DropwizardMeterRegistries` and `NoopMeterRegistries` in this PR?

**Comment by imasahiro** [comment]
Updated. 
Added NoPauseDetector except NoopMeterRegistry because I cannot find any merits to default to NoPauseDetector in NoopMeterRegistry.

**Comment by imasahiro** [comment]
Failed following test at Travis but I cannot reproduce it on my laptop. Maybe not related to my change?
```
com.linecorp.armeria.it.grpc.GrpcMetricsIntegrationTest > normal FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:622)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:122)
        at com.linecorp.armeria.grpc.testing.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:569)
        at com.linecorp.armeria.it.grpc.GrpcMetricsIntegrationTest.makeRequest(GrpcMetricsIntegrationTest.java:170)
        at com.linecorp.armeria.it.grpc.GrpcMetricsIntegrationTest.normal(GrpcMetricsIntegrationTest.java:104)
```

**Comment by trustin** [comment]
@imasahiro The failure seems unrelated. Let me re-run the build.

**Comment by trustin** [comment]
Failed again. That's weird.

**Comment by trustin** [comment]
@imasahiro I think this may be just taking longer than 10 seconds. Could you try to increase the test timeout from 10 seconds to 30 seconds for the offending test?

**Comment by trustin** [comment]
I guess you meant to increase the timeout in this PR, not in #954 ? (or both?)

**Comment by imasahiro** [comment]
Yeah, pushed to wrong branch.. Now I push to this PR branch.

**Comment by trustin** [comment]
Yay, build passed.

**Comment by trustin** [comment]
Ping @minwoox

**Comment by trustin** [comment]
Thanks, @imasahiro !

**Pull request merged**
