### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by trustin**
- Brave 3.14.1
  - Replace deprecated API usage
- gRPC 1.0.1
  - Ignore ArmeriaGrpcServerInteropTest temporarily until gRPC upgrades
    to Netty 4.1.6.
- Jackson 2.8.4
- Jetty 9.3.12.v20160915
- jsonunit 1.16.0
- Mockito 2.2.3
- Netty 4.1.6.Final
- Netty TCNative BoringSSL 1.1.33.Fork23
- Tomcat 8.5.6

### CODE REVIEW

**Comment by trustin** [comment]
@synk Please review, since it contains Brave-related changes mostly.

**Comment by synk** [comment]
LGTM!

**Comment by trustin** [comment]
@synk Then please merge. :-)

**Comment by trustin** [comment]
@synk Thanks a lot!

**Pull request merged**
