### PR TITLE
Introduce ConcurrentLimitTimeoutException

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
We shouldn't use `RequestTimeoutExceptino` on the client side.
It would be nice if we introduce a new exception that is used when a request times out in `ConcurrencyLimitingClient`.

Modification:
- Add `ConcurrentLimitTimeoutException`.

Result:
- `ConcurrentLimitTimeoutException` is now raised when a request times out in `ConcurrentLimitingClient`.

### CODE REVIEW

**Review by trustin — COMMENTED** [review]
Should we introduce a subtype of `ResponseTimeoutException` to tell a user that the timeout occurred due to concurrency limit?

**Comment by minwoox** [comment]
> Should we introduce a subtype of ResponseTimeoutException to tell a user that the timeout occurred due to concurrency limit?

That's a good suggestion.
However, how about making a separate exception such as `ConcurrencyLimitTimeoutException`?
The response timeout starts when the request is sent fully, but this isn't the case. 🤔

**Review by ikhoon — APPROVED** [review]
😱😱😱

**Comment by ikhoon** [comment]
I missed this discussion.

**Comment by trustin** [comment]
> However, how about making a separate exception such as `ConcurrencyLimitTimeoutException`?
> The response timeout starts when the request is sent fully, but this isn't the case. 🤔 

That's also fine as long as it extends `TimeoutException`.

**Comment by minwoox** [comment]
> That's also fine as long as it extends TimeoutException.

Thanks! added. 😄

**Review by ikhoon — APPROVED** [review]
Thanks! @minwoox

**Review by trustin — APPROVED** [review]
Thanks!

**Pull request merged**
