### PR TITLE
Update GraalVM native image metadata

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

GraalVM native image tool fails to generate a working binary since
Armeria 1.30.0, due to its outdated metadata. Special thanks to @Dogacel
who reported this issue.

Modifications:

- Updated the GraalVM native image metadata.
- Removed the redundent `../../` from the resource lookup in `ThriftMetadatAccess`.

Result:

Armeria is again compatible with GraalVM native image tool.

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks!

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Comment by imasahiro** [comment]
just curious, do we have a CI with GraalVM? (seems not configured yet? https://github.com/line/armeria/blob/main/.github/workflows/actions_build.yml )

**Pull request merged**
