### PR TITLE
Use Java 21 to build Armeria (+Gradle 8.7 wrapper)

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

As non-maintainer users can't update GitHub workflow files, this PR
supersedes @Dogacel's work (https://github.com/line/armeria/pull/5644)

Modifications:

- Use JDK 21 to run Armeria CI and other jobs
- Upgrade Gradle wrapper version to 8.7

Result:

You can now use Java 21 to build Armeria

Co-authored-by: Dogacel <dogacel@gmail.com>

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
Looks good to me once the build passes 👍 👍 👍

**Review by Dogacel — APPROVED** [review]
Thank you 🙇

**Review by trustin — APPROVED** [review]
Thanks a lot!

**Review by minwoox — COMMENTED** [review]
Shouldn't we also use 21 for release?
https://github.com/line/armeria/blob/ca31809a6a7c49e768a90575d7b614342af8edfa/build.gradle#L285-L289

**Comment by ikhoon** [comment]
Nice catch!

**Review by minwoox — APPROVED** [review]
Thanks, @ikhoon and @Dogacel!

**Comment by minwoox** [comment]
👍 👍 👍

**Pull request merged**
