### PR TITLE
Shade the dependencies that are not exposed in public API

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

Armeria started to have various 3rd party dependencies and it means
higher chance of version conflicts when it's used as a part of a large
application. We could reduce the risk by shading (or shadowing) the
dependencies that are not exposed in public API.

Modifications:

- Shade the following dependencies into com.linecorp.armeria.internal:
  - com.spotify:completable-futures
  - it.unimi.dsi:fastutil
  - jp.skypencil.guava:helper
  - org.reflections:reflections
- Trim unused classes from the shaded dependencies using ProGuard
  - Increase the maximum JVM heap size to 384MB to avoid OOME
- Miscellaneous:
  - Update to Gradle 3.2.1
  - Fix the file descriptor leaks and other issues in the
    'versionProperties' task

Result:

- Fewer number of external dependencies

### CODE REVIEW

**Comment by trustin** [comment]
The remaining 3rd party dependencies of armeria-core are:

- Guava
- Jackson
- Netty
- Reactive Streams
- Thrift

.. which seem reasonable to me. I'm not sure we can/should shade them. WDYT? /cc @anuraaga @inch772

**Comment by trustin** [comment]
One problem with this change is that it increases the size of armeria-core JAR by 14 megabytes.

**Comment by imasahiro** [comment]
Hmm, I checked unzipped classes and realized that fastutil is about 10 times bigger than armeria...

```sh
masa@local ~/src/armeria $  ./gradlew build && cd core/build/libs && unzip armeria-0.31.2.Final-SNAPSHOT.jar

masa@local ~/src/armeria $ du -sh ./com/linecorp/armeria/*
844K    ./com/linecorp/armeria/client
736K    ./com/linecorp/armeria/common
 64M    ./com/linecorp/armeria/internal
5.6M    ./com/linecorp/armeria/server
120K    ./com/linecorp/armeria/service

masa@local ~/src/armeria/core/build/libs$  du -sh ./com/linecorp/armeria/internal/deps/* 
 63M    ./com/linecorp/armeria/internal/deps/fastutil
 36K    ./com/linecorp/armeria/internal/deps/futures
 88K    ./com/linecorp/armeria/internal/deps/guava
500K    ./com/linecorp/armeria/internal/deps/reflections
```

**Comment by imasahiro** [comment]
According to fastutil webpage (http://fastutil.di.unimi.it/ ), it is recommended to use autojar. 

> Installation
> (snip)
> Note that the jar file is huge, due to the large number of classes: if you plan to ship your own jar with some fastutil classes included, you should look at AutoJar or similar tools. 

I found gradle plugin for this (https://github.com/rholder/gradle-autojar ) but not sure we can use this plugin because it looks not maintenanced now.

**Comment by trustin** [comment]
Perhaps I can add some exclusions and inclusions for fastutil and reflections. Will try tomorrow.

**Comment by trustin** [comment]
Going to give ProGuard a try: http://proguard.sourceforge.net/manual/examples.html#deadcode

**Comment by trustin** [comment]
@imasahiro Now using ProGuard to trim the internal dependencies. It's back to 4MB again.

**Comment by imasahiro** [comment]
I don' think we need to shade netty, jackson, ... at this time. Let me merge this PR now.

**Comment by trustin** [comment]
Thanks, @imasahiro :-)

**Pull request merged**
