### PR TITLE
Add a simple benchmark to check retrofit performance.

### PR DESCRIPTION
**Pull request by anuraaga**
For #1185 - it's good to have some benchmarks to establish a baseline. This first one doesn't intend to be representative of all use cases, but has minimal business logic to try to stress the integration itself as much as possible. Indeed seeing about a 10% improvement in performance using upstream okhttp, similar to the report.

Edit: Was stupidly creating new client every benchmark iteration, ignore emails.

```
Benchmark                                            Mode  Cnt     Score     Error  Units
c.l.a.r.downstream.DownstreamSimpleBenchmark.empty  thrpt   20  3406.076 ▒ 105.094  ops/s
c.l.a.r.upstream.UpstreamSimpleBenchmark.empty      thrpt   20  3785.867 ▒ 130.965  ops/s
```

By the way, to not feel too down, here are the results with 20 JMH threads - as expected our throughput is way better.

```
Benchmark                                            Mode  Cnt      Score     Error  Units
c.l.a.r.downstream.DownstreamSimpleBenchmark.empty  thrpt   20  12852.210 ▒ 261.126  ops/s
c.l.a.r.upstream.UpstreamSimpleBenchmark.empty      thrpt   20   7064.704 ▒ 112.538  ops/s
```

### CODE REVIEW

**Comment by anuraaga** [comment]
JFYI trying on Windows Subsystem for Linux, had the same behavior of connections never being reused. Will be able to check real Linux on Monday

**Comment by trustin** [comment]
Oops. Could you fix the conflicts, @anuraaga?

**Comment by anuraaga** [comment]
Yup, merged

**Comment by trustin** [comment]
Thank you!

**Pull request merged**
