### PR TITLE
Add seconds suffix to LONG_TASK_TIMER for legacy convention

### PR DESCRIPTION
**Pull request by huydx**
…gConvention

see https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L68-L74

### CODE REVIEW

**Comment by huydx** [comment]
oops test failed, let me fix it

**Comment by huydx** [comment]
seems failed tests are flaky one, can't reproduce at local

**Comment by minwoox** [comment]
Thank you!

**Comment by mauhiz** [comment]
oh! Good find

**Pull request merged**
