### PR TITLE
Remove anuraaga from owners

### PR DESCRIPTION
**Pull request by anuraaga**
I don't use Armeria much lately. It's still my favorite framework so I hope that changes but I think it's important for everyone that my review should not be required or expected for gRPC changes. I still watch the repo so may chime in anyways, and of course happy anytime to be added as a reviewer to a PR individually instead of automatically.

### CODE REVIEW

**Comment by anuraaga** [comment]
Apparently gRPC is crying about this change XD

**Comment by minwoox** [comment]
> I think it's important for everyone that my review should not be required

Don't agree at all. ;)
You always pointed out that I didn't think of and realize. Your comments were always helpful and led us in the right direction. So it's definitely required.

I hope this is just that you don't want to be added as a reviewer automatically because I want to see the 'Rag' moment as much as I can. 😄

**Comment by minwoox** [comment]
And the build still fails

**Comment by anuraaga** [comment]
> I hope this is just that you don't want to be added as a reviewer automatically

Yup don't worry I'll still be jumping in when the PR title sounds interesting :) But don't think others need to be blocked on it either.

**Pull request merged**
