### PR TITLE
Upgrade Caffeine to 2.6.1

### PR DESCRIPTION
**Pull request by kojilin**

### CODE REVIEW

**Comment by trustin** [comment]
@imasahiro Gentle ping

**Comment by trustin** [comment]
Thanks!

**Comment by ben-manes** [comment]
Not sure if it helps, but I wrote the first [gradle plugin](https://github.com/ben-manes/gradle-versions-plugin) to automatically discover updates (when migrating from Maven and missing its feature). The plugin just leverages Gradle's own dependency management capabilities rather than do any heavy lifting itself.

I personally prefer having a [dependencies.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle) file vs your yaml, but that's stylistic.

**Comment by anuraaga** [comment]
Yeah your plugin came up once :) https://github.com/line/armeria/pull/927

Think @trustin is looking into it and / or nebula plugin.

**Comment by ben-manes** [comment]
nebula looks good! Always been too lazy to try it since I had my own method for a few years =)

**Comment by trustin** [comment]
Tried to apply the Nebula plugins but it had some issues:

- The generated global lock file contained many duplicate entries, which are hard to read.
- Their publish setup does not work when a project publishes more than one artifact.

The motivation of adopting Nebula plugins was to remove the boilerplates related with dependency management and publication in `build.gradle` but none of them was solved as expected. 😭

**Comment by ben-manes** [comment]
In the `dependencies.gradle` style, you write the usages like.,

```gradle
compile libraries.caffeine
testCompile testLibraries.testng
```

so the coordinate is fully encapsulated. That's nice for readability and if you need to bundle a few artifacts together into one, e.g. Jackson and its extensions.

**Comment by anuraaga** [comment]
I didn't look at their publication stuff but I wonder if the experimental lock plugin would fit better (it seems much less intrusive to boot)

https://github.com/nebula-plugins/lock-experimental/blob/master/README.md

**Pull request merged**
