### PR TITLE
Add a new japanese conference video

### PR DESCRIPTION
**Pull request by policeman-kh**
Motivation:

Add a new japanese conference video. 
I made a presentation about Armeria integration of LINE STORE at the Japanese conference, [Spring Fest 2021](https://springfest2021.springframework.jp/) this month, and then the youtube video is posted. 
I would like to share it as the community slide and video.

Modifications:

- Add a new `Article` tag for it.

Result:

- The `Article` is shown in the following image.
スクリーンショット 2021-12-24 15 41 21

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
❤️

**Review by jrhee17 — APPROVED** [review]
Thank you @policeman-kh ! ❤️ 🙇 👍

**Review by ikhoon — APPROVED** [review]
Looks informative for Japanese speakers. ❤️ (I can't read Japanese though. 😅)

**Comment by policeman-kh** [comment]
Sorry... I found TYPO. 
> /MVS/MVC/ 
Let me fix it.

**Comment by minwoox** [comment]
Thanks, @policeman-kh! 🎉 🎉 🎉

**Pull request merged**
