### PR TITLE
Remove ZooKeeperEndpointGroup#Mode

### LINKED ISSUE #1005: Mode.IN_NODE_VALUE in Zookeeper-based service discovery is meaningless
I found this problem while I was working on #882.

1. The constructor of `ZooKeeperUpdatingListener` (and underlying `ZooKeeperRegistration`) does not provide a way to specify `Mode` to use; Actually, its value is fixed to `Mode.IN_CHILD_NODES` and there is no way to change it.
2. `ZooKeeperRegistrationTest` also tests the case of `Mode.IN_CHILD_NODES` only.
3. Even if `ZooKeeperUpdatingListener` and `ZooKeeperRegistration` support `Mode` parameter, there is another problem: Zookeeper can't detect whether the server registered in node value is alive; Since it is a value of Persistent Node.

So: `Mode` should be removed and [the documentation](https://github.com/line/armeria/tree/master/site/src/sphinx/advanced-zookeeper.rst) should also be updated, before progressing #882. (In that update, Zookeeper-based service discovery feature is implemented with `CuratorFramework` instance only.)

### PR DESCRIPTION
**Pull request by dongjinleekr**
Resolves #1005, with a typo fix.

### CODE REVIEW

**Comment by trustin** [comment]
Time to sign your ICLA: https://feedback.line.me/enquete/public/799-Z6ygVz3U

**Comment by dongjinleekr** [comment]
Completed.

**Comment by trustin** [comment]
@dongjinleekr Mailing address has to be your physical address. Could you sign again?

**Comment by dongjinleekr** [comment]
OMG, sorry; I did it again.

**Comment by dongjinleekr** [comment]
I also reported a following issue: #1007

**Comment by trustin** [comment]
Thanks, @dongjinleekr !

**Pull request merged**
