### PR TITLE
Grant @dependabot write permission for workflow files.

### PR DESCRIPTION
**Pull request by ikhoon**
Because @dependabot sends pull requests to update the versions of GitHub Actions plugins in workflow files.

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
👍

**Comment by jrhee17** [comment]
Question) Has this been reflected in our CI machines also?  A fresh PR from today also seemed to have failed: https://github.com/line/armeria/pull/5429

**Comment by ikhoon** [comment]
I updated the script on the CI machines yesterday. Let me take a closer look.

**Comment by ikhoon** [comment]
> @dependabot[bot] is not a maintainer. Disallowed to change GitHub Actions workflows.

Oops... the name is different. I realized that GitHub appends `[bot]` suffix to bot accounts. 😅

**Comment by ikhoon** [comment]
Created https://github.com/line/armeria/pull/5431

**Pull request merged**
