### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by trustin**
- Brave 4.9.2 -> 4.10.0
- Checkstyle 8.4 -> 8.5
- Guava 23.4 -> 23.5
- Micrometer 1.0.0-rc.4 -> 1.0.0-rc.5

### CODE REVIEW

**Comment by anuraaga** [comment]
Did you find a reason not to update gRPC to 1.8.0? You mentioned tracing but not sure if it affects us (just tried running tests with 1.8.0 and they seemed to pass)

**Comment by trustin** [comment]
@anuraaga There were compilation errors and I didn't have time to take a close look.

**Comment by trustin** [comment]
@anuraaga If you got it working, then please feel free to send a PR. :-)

**Comment by anuraaga** [comment]
Sent :)

**Pull request merged**
